"""
Making summarizing plots for multiple SLiM runs, using the tables generated by
alleleAge_slimHistory_fpr.py
tianlin.duan42@gmail.com
2024.07.23
"""
############################# modules #########################################
import matplotlib
import msprime
import tskit
import pyslim
import matplotlib
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.spatial import distance_matrix
import numpy as np
import random
from time import time
import sys # for sys.exit()
import allel # for allel.weir_cockerham_fst()
import glob #for loading files
from collections import Counter
import pandas as pd #dataframe
import os #mkdir
# matplotlib.use("qt5agg") # Not work
import matplotlib.pyplot as plt
# import seaborn
import scipy.stats as stats
import sys # for sys.exit()
import allel # for allel.weir_cockerham_fst()
import matplotlib.patches as mpatches # manually make legends
import seaborn as sns # for density histplot

############################# options #############################
# import argparse
#
# parser = argparse.ArgumentParser()
# parser.add_argument('-i', '--input',
#                     help='Path to input tables',
#                     type=str)
# # parser.add_argument('-n', '--name',
# #                     help='Short model name',
# #                     type=str)
# # parser.add_argument('-p', '--plot',
# #                     help='1 for generating plots and 0 for not plotting',
# #                     type=int, default=1)
# args = parser.parse_args()

############################# program #########################################
# Values
# sigma_w = 0.4
# dist_mate = 0.12
num_runs = 100
# inPath = args.input

# mytitle = "M0a, low migration, cline map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
# mytitle = "M0a, high migration, cline map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K5000_r1.0e-07/tick110000/"
# mytitle = "M0a, low migration, patchy map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0a_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
# mytitle = "M0a, high migration, patchy map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0a_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K5000_r1.0e-07/tick110000/"
# mytitle = "M0b, low migration, cline map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
# mytitle = "M0b, high migration, cline map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K5000_r1.0e-07/tick110000/"
# mytitle = "M0b, low migration, patchy map"
# inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
mytitle = "M0b, high migration, patchy map"
inPath = "/media/anadem/PortableSSD/arg4gea_data/UBC_dell_20240917/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K5000_r1.0e-07/tick110000/"

simName = inPath.split("/")[-3]
#Short title: Hard coded. Check this before using!
if "sigmaD0.06_mateD0.15" in simName:
    migName = "HighMig"
elif "sigmaD0.03_mateD0.12" in simName:
    migName = "LowMig"
else:
    migName = ""
if "_clineMap_" in simName:
    mapName = "Cline"
elif "_patchyMap_" in simName:
    mapName = "Patchy"
else:
    mapName = ""
if "_sigmaM0.01_" in simName:
    mutName = "highPoly"
elif "_sigmaM0.1_" in simName:
    mutName = "lowPoly"
else:
    mutName = ""
demoName = simName.split("_")[2]
shortName = ",".join([demoName, migName, mapName])

# figPath = ("/home/tianlin/Documents/github/data/tskit_data/figure/20240909/" +
#            simName + "/" + str(num_runs) + "runs_" + "cat100_" +
#            inPath.split("/")[-2]+"/")
figPath = ("/home/anadem/github/data/tskit_data/figure/multiRuns/p1e-10/" +
           simName + "/" + str(num_runs) + "runs_" +
           inPath.split("/")[-2]+"/")
outPath = ("/home/anadem/github/data/tskit_data/output/mutiRuns/test/")
if not os.path.exists(outPath):
    os.makedirs(outPath)
# outPath = ("/home/tianlin/Documents/github/data/tskit_data/output/multiple_runs/" +
#            simName + "/100runs_" + inPath.split("/")[-2]+"/")
# if not os.path.exists(outPath):
#     os.makedirs(outPath)
if not os.path.exists(figPath):
    os.makedirs(figPath)

# Check this before use!
model_name = "_".join(inPath.split("/")[-3:-1] + [str(num_runs)+"runs_"])
tick = int(inPath.split("/")[-2].split("tick")[-1])
event_age = tick - 100000

# Load results of multiple runs from file
df = pd.DataFrame()
fileList = glob.glob(inPath + "*.txt")
run = 0
for f in fileList:
    df_focal = pd.read_csv(f, sep='\t', header=0)
    # Add temporary run ID, and rank of p-values
    df_focal["run_id"] = np.full(shape=(df_focal.shape[0], 1),
                                         fill_value=run)
    # df_focal["p_rank"] = df_focal["p-tau"].argsort().argsort()
    df_focal["p-tau_rank"] = df_focal["p-tau"].rank(ascending=True, pct=True)
    df = pd.concat([df, df_focal], axis=0)
    run += 1
print(str(run) + " files have been loaded.")
# Columns: "pos", "age", "freq", "mut_effect","mean_LF",
#          "tau", "p-tau", "pearsonsrho", "p-rho",
#          "run_id", "p-tau_rank"



#### Separate neutral alleles
# mutation ID, allele age, allele frequency, mutation effect, LF_mut,
# GEA Kendall's tau and corresponding p-value

# Separate neutral alleles
df_neutral = df[(df["mut_effect"] == 0) &
                (df["freq"] != 0) &
                (df["freq"] != 1)]
# False positive rate for NEUTRAL mutations among AGE categories: Equal intervals
# Minor allele frequency filter
# maf_filter = 0
maf_filter = 0.05
df_plot = df_neutral[(df_neutral["freq"] >= maf_filter) &
                     (df_neutral["freq"] <= (1-maf_filter))]

num_cat_age = 22
# p_threshold = 0.0001
p_threshold = 0.0000000001
max_age = tick
cat_width_age = max_age/num_cat_age
age_boundaries = np.append(np.arange(0, max_age, cat_width_age), max_age)
FPR_neutral_byAge_equalWidth = []
sample_size_age_equalWidth = []
p_median_byAge_equalWidth = []
p_sd_byAge_equalWidth = []
tau_absMedian_byAge_equalWidth = []
tau_absSd_byAge_equalWidth = []
for i in range(num_cat_age):
    p_category = df_plot["p-tau"][(df_plot["age"] > age_boundaries[i]) &
                                 (df_plot["age"] <= age_boundaries[i+1])]
    tau_category = df_plot["tau"][(df_plot["age"] > age_boundaries[i]) &
                                 (df_plot["age"] <= age_boundaries[i+1])]
    sample_size_age_equalWidth.append(len(p_category))
    p_median_byAge_equalWidth.append(np.nanmedian(p_category))
    p_sd_byAge_equalWidth.append(np.nanstd(p_category))
    tau_absMedian_byAge_equalWidth.append(np.nanmedian(abs(tau_category)))
    tau_absSd_byAge_equalWidth.append(np.nanstd(abs(tau_category)))
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < p_threshold
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byAge_equalWidth.append(FP/mut_in_cat)

del df_plot

#Save the FPR~age table for combined figures
outPath_fpr = outPath + "fpr/singleModel/"
x = age_boundaries[0:-1] + cat_width_age/2
y = FPR_neutral_byAge_equalWidth
if not os.path.exists(outPath_fpr):
    os.makedirs(outPath_fpr)
out_path_file = (outPath_fpr + model_name +
                 "p" + str(p_threshold) +
                 "_maf"+str(maf_filter) +
                 "_cat" + str(num_cat_age)+ "_fpr.tab")
header = "\t".join(["age", "fpr", "tick_text"]) + "\n"
with open(out_path_file, "w") as fout:
    fout.write(header)
    for i in range(len(x)):
        outLine = "\t".join([str(x[i]), str(y[i]), str(age_boundaries[i])]) + "\t" +"\n"
        fout.write(outLine)
fout.close()
print("FPR table has been saved.")



#### Separate low-frequency alleles as in empirical studies
thresholdRare = 0.01
thresholdLow = 0.05
# MAF > 0.05
df_high = df_neutral[(df_neutral["freq"] >= thresholdLow) &
                     (df_neutral["freq"] <= (1-thresholdLow))]
# 0.01 < MAF < 0.05
df_low = df_neutral[(df_neutral["freq"] <= thresholdLow) &
                    (df_neutral["freq"] >= thresholdRare) |
                    (df_neutral["freq"] <= (1-thresholdRare)) &
                    (df_neutral["freq"] >= (1-thresholdLow))]
# 0 < MAF < 0.01
df_rare = df_neutral[(df_neutral["freq"] <= thresholdRare) |
                     (df_neutral["freq"] >= (1-thresholdRare))]
# num_neutral_muts = df_neutral.shape[0]

# Check here before use
num_cat = 100
bin_width = 100/num_cat

# # p,tau and false negative rate for NEUTRAL mutations among AGE categories
# # Equal numbers
# cat_width = int(100/num_cat) if 100 % num_cat == 0 else 100/num_cat
# age_percentile = np.percentile(df_neutral["age"],
#                                np.append(np.arange(0, 100, cat_width),
#                                          100))
# FPR_neutral_byAge = []
# p_median_byAge = []
# p_sd_byAge = []
# tau_absMedian_byAge = []
# tau_absSd_byAge = []
# for i in range(num_cat):
#     p_category = df_neutral["p-tau"][(df_neutral["age"] > age_percentile[i]) &
#                                  (df_neutral["age"] <= age_percentile[i+1])]
#     tau_category = df_neutral["tau"][(df_neutral["age"] > age_percentile[i]) &
#                                  (df_neutral["age"] <= age_percentile[i + 1])]
#     p_median_byAge.append(np.median(p_category))
#     p_sd_byAge.append(np.std(p_category))
#     tau_absMedian_byAge.append(np.median(abs(tau_category)))
#     tau_absSd_byAge.append(np.std(abs(tau_category)))
#     # Neutral mutations have no phenotypic effect and therefore no positive
#     mut_in_cat = len(p_category)
#     obsP_neutral = p_category < 0.05
#     # All positives are false positives
#     FP = sum(obsP_neutral)
#     FPR_neutral_byAge.append(FP/mut_in_cat)

# # False negative rate for NEUTRAL mutations among FREQUENCY categories
# # Equal numbers
# # Neutral mutations have no phenotypic effect and therefore no positve
# cat_width = int(100/num_cat) if 100 % num_cat == 0 else 100/num_cat
# freq_percentile = np.percentile(df_neutral["freq"],
#                                np.append(np.arange(0, 100, cat_width),100))
# FPR_neutral_byFreq = []
# p_median_byFreq = []
# p_sd_byFreq = []
# tau_absMedian_byFreq = []
# tau_absSd_byFreq = []
# for i in range(num_cat):
#     p_category = df_neutral["p-tau"][
#         (df_neutral["freq"] > freq_percentile[i]) &
#         (df_neutral["freq"] <= freq_percentile[i+1])]
#     tau_category = df_neutral["tau"][
#         (df_neutral["freq"] > freq_percentile[i]) &
#         (df_neutral["freq"] <= freq_percentile[i + 1])]
#     p_median_byFreq.append(np.median(p_category))
#     p_sd_byFreq.append(np.std(p_category))
#     tau_absMedian_byFreq.append(np.median(abs(tau_category)))
#     tau_absSd_byFreq.append(np.std(abs(tau_category)))
#     # Neutral mutations have no phenotypic effect and therefore no positive
#     mut_in_cat = len(p_category)
#     obsP_neutral = p_category < 0.05
#     # All positives are false positives
#     FP = sum(obsP_neutral)
#     FPR_neutral_byFreq.append(FP/mut_in_cat)

# False negative rate for NEUTRAL mutations among FREQ categories: Equal intervals
num_cat_freq = 40
p_threshold = 0.0001
# p_threshold = 0.0000000001
cat_width_freq = 1.0/num_cat_freq
freq_boundaries = np.append(np.arange(0, 1.0, cat_width_freq), 1.0)
FPR_neutral_byFreq_equalWidth = []
sample_size_freq_equalWidth = []
p_median_byFreq_equalWidth = []
p_sd_byFreq_equalWidth = []
tau_absMedian_byFreq_equalWidth = []
tau_absSd_byFreq_equalWidth = []
for i in range(num_cat_freq):
    p_category = df_neutral["p-tau"][(df_neutral["freq"] > freq_boundaries[i]) &
                                 (df_neutral["freq"] <= freq_boundaries[i+1])]
    tau_category = df_neutral["tau"][(df_neutral["freq"] > freq_boundaries[i]) &
                                 (df_neutral["freq"] <= freq_boundaries[
                                     i + 1])]
    print(len(p_category))
    sample_size_freq_equalWidth.append(len(p_category))
    p_median_byFreq_equalWidth.append(np.nanmedian(p_category))
    p_sd_byFreq_equalWidth.append(np.nanstd(p_category))
    tau_absMedian_byFreq_equalWidth.append(np.nanmedian(abs(tau_category)))
    tau_absSd_byFreq_equalWidth.append(np.nanstd(abs(tau_category)))
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < p_threshold
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byFreq_equalWidth.append(FP/mut_in_cat)

# # False negative rate for NEUTRAL mutations among FREQ categories:
# # log10 Equal intervals
# num_cat_freq = 20
# cat_width_freq_log10 = 4.0/num_cat_freq
# freq_boundaries_log10 = 10**(np.append(np.arange(-4.0, 0,
#                                                  cat_width_freq_log10),
#                                        0))
# FPR_neutral_byFreq_equalWidth_log10 = []
# sample_size_freq_equalWidth_log10 = []
# p_median_byFreq_equalWidth_log10 = []
# p_sd_byFreq_equalWidth_log10 = []
# tau_absMedian_byFreq_equalWidth_log10 = []
# tau_absSd_byFreq_equalWidth_log10 = []
# for i in range(num_cat_freq):
#     p_category = df_neutral["p-tau"][(df_neutral["freq"] > freq_boundaries_log10[i]) &
#                                  (df_neutral["freq"] <= freq_boundaries_log10[i+1])]
#     tau_category = df_neutral["tau"][(df_neutral["freq"] > freq_boundaries_log10[i]) &
#                                  (df_neutral["freq"] <= freq_boundaries_log10[
#                                      i + 1])]
#     print(len(p_category))
#     sample_size_freq_equalWidth_log10.append(len(p_category))
#     p_median_byFreq_equalWidth_log10.append(np.nanmedian(p_category))
#     p_sd_byFreq_equalWidth_log10.append(np.nanstd(p_category))
#     tau_absMedian_byFreq_equalWidth_log10.append(np.nanmedian(abs(tau_category)))
#     tau_absSd_byFreq_equalWidth_log10.append(np.nanstd(abs(tau_category)))
#     # Neutral mutations have no phenotypic effect and therefore no positive
#     mut_in_cat = len(p_category)
#     obsP_neutral = p_category < p_threshold
#     # All positives are false positives
#     FP = sum(obsP_neutral)
#     FPR_neutral_byFreq_equalWidth_log10.append(FP/mut_in_cat)



#### Plots ####
# # Histogram of allele age of neutral alleles
# plt.hist(df_neutral["age"], bins=100,
#          color="grey")
# plt.xlabel("Allele age")
# plt.ylabel("Count")
# plt.savefig(figPath+model_name+"_age_hist_neutral.png",
#             dpi=300)
# plt.close()
#
# # Histogram of allele freq of neutral alleles
# plt.hist(df_neutral["freq"], bins=100,
#          color="grey")
# plt.xlabel("Allele frequency")
# plt.ylabel("Count")
# plt.savefig(figPath+model_name+"_freq_hist_neutral.png",
#             dpi=300)
# plt.close()


# #### Equal number of alleles per bin ####
# # Neutral alleles: FPR ～ Allele age, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(int(j)) for i,j in zip(x_ticks, age_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          FPR_neutral_byAge,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele age percentile bins")
# plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_FPR_GEAp0.05_vs_age_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: p_median ～ Allele age, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(int(j)) for i,j in zip(x_ticks, age_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          p_median_byAge,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele age percentile bins")
# plt.ylabel("Median p-values of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAmedianP_vs_age_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: p_sd ～ Allele age, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(int(j)) for i,j in zip(x_ticks, age_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          p_sd_byAge,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele age percentile bins")
# plt.ylabel("Standard deviation of p-values of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAsdP_vs_age_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: tau_abs_median ～ Allele age, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(int(j)) for i,j in zip(x_ticks, age_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          tau_absMedian_byAge,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele age percentile bins")
# plt.ylabel("Median |Kendall's tau| of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAmedianTau_vs_age_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: tau_abs_sd ～ Allele age, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(int(j)) for i,j in zip(x_ticks, age_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          tau_absSd_byAge,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele age percentile bins")
# plt.ylabel("Standard deviation of |Kendall's tau| of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAsdTau_vs_age_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: FPR ～ Frequency, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(round(j,2))
#             for i,j in zip(x_ticks, freq_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          FPR_neutral_byFreq,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele frequency percentile bins")
# plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_FPR_GEAp0.05_vs_freq_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: p_median ～ Allele frequency, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(round(j,2)) for i,j in zip(x_ticks, freq_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          p_median_byFreq,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele frequency percentile bins")
# plt.ylabel("Median p-values of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAmedianP_vs_freq_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: p_sd ～ Allele frequency, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(round(j,2)) for i,j in zip(x_ticks, freq_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          p_sd_byFreq,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele frequency percentile bins")
# plt.ylabel("Standard deviation of p-values of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAsdP_vs_freq_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: tau_abs_median ～ Allele frequency, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(round(j,2)) for i,j in zip(x_ticks, freq_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          tau_absMedian_byFreq,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele frequency percentile bins")
# plt.ylabel("Median |Kendall's tau| of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAmedianTau_vs_freq_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()
#
# # Neutral alleles: tau_abs_sd ～ Allele frequency, equal number alleles per bin
# x_ticks = np.append(np.arange(0, 100, cat_width),100)
# x_labels = [str(i)+"\n"+str(round(j,2)) for i,j in zip(x_ticks, freq_percentile)]
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat) - 0.5*bin_width,
#          tau_absSd_byFreq,
#          color="grey",
#          marker = "o")
# plt.xlabel("\nAllele frequency percentile bins")
# plt.ylabel("Standard deviation of |Kendall's tau| of neutral alleles")
# plt.xticks(ticks=x_ticks,
#            labels=x_labels)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_GEAsdTau_vs_freq_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()

# # Neutral alleles: FPR ～ Frequency, equal number alleles per bin
# plt_pos = np.arange(100/num_cat, 101, 100/num_cat) - 5
# plt.plot(plt_pos,
#          FPR_neutral_byFreq,
#          color="grey",
#          marker = "o")
# plt.xlabel("\n\n\nAllele frequency percentile bins")
# # plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
# plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
# for i in range(num_cat + 1):
#     label = "{:.5f}".format(freq_percentile[i])
#     print(label)
#     x = np.arange(0, 101+bin_width, 100/num_cat)[i]
#     y = -0.30 * max(FPR_neutral_byFreq)
#     plt.annotate(label,
#                  (x,y),
#                  textcoords="offset points",
#                  xytext=(-1*bin_width, 0.5*bin_width),
#                  annotation_clip=False,
#                  color="grey",
#                  rotation = 45)
#     plt.xticks([], minor=False)
# plt.xticks(ticks=np.arange(0, 101, 100/num_cat),
#            labels=[str(int(i*cat_width)) for i in range(num_cat+1)])
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins"+"_FPR_GEAp0.05_vs_freq_neutralAllele_equalNumber.png",
#             dpi=300)
# plt.close()



#### Equal intervals ####
# age_fig_size = (8,5) # 20 bins
age_fig_size = (8,5) # 40 bins
# age_fig_size = (15,5) # 100 bins

# Neutral alleles: FPR ～ Allele age, equal width
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(age_boundaries[0:-1] + cat_width_age/2,
         FPR_neutral_byAge_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele age", fontsize=14)
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=14)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i)) for i in age_boundaries],
           rotation=90)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat_age)+"bins"+"_FPR_GEAp" + str(p_threshold) +
            "_maf" + str(maf_filter) +
            "_vs_age_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: p_median ～ Allele age, equal width
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(age_boundaries[0:-1] + cat_width_age/2,
         p_median_byAge_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele age",
           fontsize=14)
plt.ylabel("Median p-values of neutral alleles",
           fontsize=14)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i)) for i in age_boundaries],
           rotation=90)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_maf" + str(maf_filter) +
            "_GEAmedianP_vs_age_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: p_sd ～ Allele age, equal width
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(age_boundaries[0:-1] + cat_width_age/2,
         p_sd_byAge_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele age",
           fontsize=14)
plt.ylabel("Standard deviation of p-values \n of neutral alleles",
           fontsize=14)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i)) for i in age_boundaries],
           rotation=90)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_maf" + str(maf_filter) +
            "_GEAsdP_vs_age_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: tau_abs_median ～ Allele age, equal width
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(age_boundaries[0:-1] + cat_width_age/2,
         tau_absMedian_byAge_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele age",
           fontsize=14)
plt.ylabel("Median |Kendall's tau| of neutral alleles",
           fontsize=14)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i)) for i in age_boundaries],
           rotation=90)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_maf" + str(maf_filter) +
            "_GEAmedianTau_vs_age_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: tau_abs_sd ～ Allele age, equal width
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(age_boundaries[0:-1] + cat_width_age/2,
         tau_absSd_byAge_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele age",
           fontsize=14)
plt.ylabel("Standard deviation of |Kendall's tau| \n of neutral alleles",
           fontsize=14)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i)) for i in age_boundaries],
           rotation=90)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_maf" + str(maf_filter) +
            "_GEAsdTau_vs_age_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()



# Neutral alleles: FPR ～ Allele frequency, equal intervals
freq_fig_size = (8,5) # 20 bins
# freq_fig_size = (15,5) # 100 bins
freq_axis_size = 14
label_rotation = 80

plt.figure(figsize=freq_fig_size)
plt.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         FPR_neutral_byFreq_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele frequency",
           fontsize=freq_axis_size)
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=freq_axis_size)
plt.xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath + model_name +
            str(num_cat_freq)+"bins"+"_FPR_GEAp" + str(p_threshold) +
            "_vs_freq_neutralAllele_equalInterval.png",
            # str(num_cat_freq) + "bins" + "_FPR_GEAp0.05_vs_freq_neutralAllele_equalInterval_log10cat.png",
            dpi=300)
plt.close()

# Neutral alleles: p_median ～ Allele freq, equal width
plt.figure(figsize=freq_fig_size)
plt.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         p_median_byFreq_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele frequency",
           fontsize=freq_axis_size)
plt.ylabel("Median p-values of neutral alleles",
           fontsize=freq_axis_size)
plt.xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_GEAmedianP_vs_freq_neutralAllele_equalInterval.png",
            # "_GEAmedianP_vs_freq_neutralAllele_equalInterval_log10cat.png",
            dpi=300)
plt.close()

# # log10 freq
# # Neutral alleles: FPR ～ Allele frequency, equal intervals
# freq_fig_size = (8,5) # 20 bins
# # freq_fig_size = (15,5) # 100 bins
# freq_axis_size = 14
# label_rotation = 80
#
# plt.figure(figsize=freq_fig_size)
# plt.plot(np.log10(freq_boundaries_log10[0:-1]),
#          FPR_neutral_byFreq_equalWidth_log10,
#          color="grey",
#          marker = "o")
# plt.xlabel("Log10(allele frequency)",
#            fontsize=freq_axis_size)
# # plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
# plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
#            fontsize=freq_axis_size)
# # plt.xticks(ticks=freq_boundaries,
# #            labels=[str(round(i,2)) for i in freq_boundaries],
# #            rotation=label_rotation)
# plt.title(shortName)
# plt.tight_layout()
# plt.savefig(figPath + model_name +
#             # str(num_cat_freq)+"bins"+"_FPR_GEAp0.05_vs_freq_neutralAllele_equalInterval.png",
#             str(num_cat_freq) + "bins" +
#             "_maf" + str(maf_filter) +
#             "_FPR_GEAp0.05_vs_freq_neutralAllele_equalInterval_log10cat.png",
#             dpi=300)
# plt.close()
#
# # log10 freq
# # Neutral alleles: p_median ～ Allele freq, equal width
# plt.figure(figsize=freq_fig_size)
# plt.plot(np.log10(freq_boundaries_log10[0:-1]),
#          p_median_byFreq_equalWidth_log10,
#          color="grey",
#          marker = "o")
# plt.xlabel("Log10(allele frequency)",
#            fontsize=freq_axis_size)
# plt.ylabel("Median p-values of neutral alleles",
#            fontsize=freq_axis_size)
# # plt.xticks(ticks=freq_boundaries,
# #            labels=[str(round(i,2)) for i in freq_boundaries],
# #            rotation=label_rotation)
# plt.title(shortName)
# plt.tight_layout()
# plt.savefig(figPath+model_name +
#             str(num_cat)+"bins" +
#             "_maf" + str(maf_filter) +
#             # "_GEAmedianP_vs_freq_neutralAllele_equalInterval.png",
#             "_GEAmedianP_vs_freq_neutralAllele_equalInterval_log10cat.png",
#             dpi=300)
# plt.close()



# Neutral alleles: p_sd ～ Allele freq, equal width
plt.figure(figsize=freq_fig_size)
plt.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         p_sd_byFreq_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele frequency",
           fontsize=freq_axis_size)
plt.ylabel("Standard deviation of p-values \n of neutral alleles",
           fontsize=freq_axis_size)
plt.xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_GEAsdP_vs_freq_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: tau_abs_median ～ Allele freq, equal width
plt.figure(figsize=freq_fig_size)
plt.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         tau_absMedian_byFreq_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele frequency",
           fontsize=freq_axis_size)
plt.ylabel("Median |Kendall's tau| \n of neutral alleles",
           fontsize=freq_axis_size)
plt.xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_GEAmedianTau_vs_freq_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: tau_abs_sd ～ Allele frequency, equal width
plt.figure(figsize=freq_fig_size)
plt.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         tau_absSd_byFreq_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele frequency",
           fontsize=freq_axis_size)
plt.ylabel("Standard deviation of |Kendall's tau| \n of neutral alleles",
           fontsize=freq_axis_size)
plt.xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
plt.title(shortName)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins" +
            "_GEAsdTau_vs_freq_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()


# Histogram of p-values
my_alpha = 0.8
my_bins = 50
histColors = ["lightblue", "slateblue", "mediumvioletred"]
plt.hist([df_rare["p-tau"],df_low["p-tau"],df_high["p-tau"]],
         bins=my_bins,
         color=histColors, alpha=my_alpha,
         histtype='bar', #histtype="step",
         label=["MAF<0.01", "0.01<MAF<0.05", "MAF>0.05"],
         density=True)
plt.xlabel("P-values")
plt.ylabel("Density")
plt.title(shortName)
plt.legend()
plt.savefig(figPath+model_name+
            "_p_hist_test5.png",
            dpi=300)
plt.close()

# Histogram of p-values for Kendall's tau
my_alpha = 0.8
my_bins = 20
histColors = ["lightblue", "mediumslateblue", "mediumvioletred"]
plt.hist([df_rare["p-tau"],df_low["p-tau"],df_high["p-tau"]],
         bins=my_bins,
         color=histColors, alpha=my_alpha,
         histtype='bar', #histtype="step",
         label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
         density=True)
plt.xlabel(r"P-value for Kendall's $\tau$")
plt.ylabel("Density")
plt.title(shortName)
plt.legend()
plt.savefig(figPath+model_name+
            "_p_kendalltau_hist.png",
            dpi=300)
plt.close()

# Histogram of p-values for Pearson's r
plt.hist([df_rare["p-rho"],df_low["p-rho"],df_high["p-rho"]],
         bins=my_bins,
         color=histColors, alpha=my_alpha,
         histtype='bar', #histtype="step",
         label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
         density=True)
plt.xlabel("P-value for Pearson's r")
plt.ylabel("Density")
plt.title(shortName)
plt.legend()
plt.savefig(figPath+model_name+
            "_p_pearsonrho_hist.png",
            dpi=300)
plt.close()


# Combine plots
# Frequency
myfigsize = (7, 6)
histColors = ["lightblue", "mediumslateblue", "mediumvioletred"]
freq_axis_size = 10
fig, ((ax0, ax1), (ax2, ax3)) = plt.subplots(nrows=2, ncols=2,
                                             figsize=myfigsize)
fig.suptitle(mytitle)
# Subplot0: p_median ～ Allele freq, equal width
ax0.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         p_median_byFreq_equalWidth,
         color="grey",
         marker = "o")
ax0.set_xlabel("Allele frequency",
           fontsize=freq_axis_size)
ax0.set_ylabel(r"Median p-values for Kendall's $\tau$"+
               "\n of neutral alleles",
           fontsize=freq_axis_size)
ax0.set_xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
# Subplot1: tau_median ～ Allele freq, equal width
ax1.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         tau_absMedian_byFreq_equalWidth,
         color="grey",
         marker = "o")
ax1.set_xlabel("Allele frequency",
           fontsize=freq_axis_size)
ax1.set_ylabel(r"Median |Kendall's $\tau$|"+ "\n of neutral alleles",
           fontsize=freq_axis_size)
ax1.set_xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
# subplot3: FPR
ax2.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         FPR_neutral_byFreq_equalWidth,
         color="grey",
         marker = "o")
ax2.set_xlabel("Allele frequency",
           fontsize=freq_axis_size)
ax2.set_ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=freq_axis_size)
ax2.set_xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=label_rotation)
# Subplot: histgrams of p-values
# ax3.hist([df_rare["p-rho"],df_low["p-rho"],df_high["p-rho"]],
#          bins=my_bins,
#          color=histColors, alpha=my_alpha,
#          histtype='bar', #histtype="step",
#          label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
#          density=True)
# ax3.set_xlabel("P-value for Pearson's r")
ax3.hist([df_rare["p-tau"],df_low["p-tau"],df_high["p-tau"]],
         bins=my_bins,
         color=histColors, alpha=my_alpha,
         histtype='bar', #histtype="step",
         label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
         density=True)
ax3.set_xlabel(r"P-value for Kendall's $\tau$")
ax3.set_ylabel("Density")
ax3.legend()
fig.tight_layout()
plt.savefig(figPath + model_name +
            str(num_cat_freq)+"bins"+
            "_maf" + str(maf_filter) +
            "_freq_fourPlots.png",
            dpi=300)
plt.close()

# Only histograms of p-values
worktitle = mytitle + "\n"
myfigsize = (7, 4)
histColors = ["lightblue", "mediumslateblue", "mediumvioletred"]
freq_axis_size = 10

fig, (ax0, ax1) = plt.subplots(nrows=1, ncols=2,
                                 figsize=myfigsize)
fig.suptitle(worktitle)
# Subplot: histgrams of p-values
# Kendall's tau
ax0.hist([df_rare["p-tau"],df_low["p-tau"],df_high["p-tau"]],
         bins=my_bins,
         color=histColors, alpha=my_alpha,
         histtype='bar', #histtype="step",
         label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
         density=True)
ax0.set_xlabel(r"P-value for Kendall's $\tau$")
ax0.set_ylabel("Density")
# ax0.legend()
# Pearson's rho
ax1.hist([df_rare["p-rho"],df_low["p-rho"],df_high["p-rho"]],
         bins=my_bins,
         color=histColors, alpha=my_alpha,
         histtype='bar', #histtype="step",
         label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
        density=True)
ax1.set_xlabel("P-value for Pearson's r")
ax1.set_ylabel("Density")
handles, labels = ax1.get_legend_handles_labels()
fig.legend(handles, labels, loc=(0.15,0.85),
           ncol=3)
fig.tight_layout()
plt.savefig(figPath + model_name +
            str(num_cat_freq)+"bins"+
            "_maf" + str(maf_filter) +
            "_pHist_2Plots.png",
            dpi=300)
plt.close()

# # Only histograms of p-values
# # Seaborn version
# d = {"values": df_rare["p-tau"]+df_low["p-tau"]+df_high["p-tau"],
#      "labels": (["0.05<MAF<1"]*len(df_rare["p-tau"]) +
#                 ["0.01<MAF<0.05"]*len(df_low["p-tau"])+
#                 ["0.05<MAF<1"]*len(df_high["p-tau"]))}
# df_plot = pd.date_range(data=d)
# worktitle = mytitle + "\n"
# myfigsize = (7, 4)
# histColors = ["lightblue", "mediumslateblue", "mediumvioletred"]
# freq_axis_size = 10
#
# fig, (ax0, ax1) = plt.subplots(nrows=1, ncols=2,
#                                  figsize=myfigsize)
# fig.suptitle(worktitle)
# # Subplot: histgrams of p-values
# # Kendall's tau
# ax0.hist([df_rare["p-tau"],df_low["p-tau"],df_high["p-tau"]],
#          bins=my_bins,
#          color=histColors, alpha=my_alpha,
#          histtype='bar', #histtype="step",
#          label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
#          density=True)
# ax0.set_xlabel(r"P-value for Kendall's $\tau$")
# ax0.set_ylabel("Density")
# # ax0.legend()
# # Pearson's rho
# # ax1.hist([df_rare["p-rho"],df_low["p-rho"],df_high["p-rho"]],
# #          bins=my_bins,
# #          color=histColors, alpha=my_alpha,
# #          histtype='bar', #histtype="step",
# #          label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
# #         density=True)
# seaborn.histplot([df_rare["p-rho"],df_low["p-rho"],df_high["p-rho"]],
#          bins=my_bins,
#          color=histColors, alpha=my_alpha,
#          # histtype='bar', #histtype="step",
#          # label=["0<MAF<0.01", "0.01<MAF<0.05", "0.05<MAF<1"],
#         stat="probability",
#                  ax=ax1)
# ax1.set_xlabel("P-value for Pearson's r")
# ax1.set_ylabel("Density")
# handles, labels = ax1.get_legend_handles_labels()
# fig.legend(handles, labels, loc=(0.15,0.85),
#            ncol=3)
# fig.tight_layout()
# plt.savefig(figPath + model_name +
#             str(num_cat_freq)+"bins"+"_pHist_2Plots.png",
#             dpi=300)
# plt.close()



