"""
Making summarizing plots for multiple SLiM runs, using the tables generated by
alleleAge_slimHistory.py
tianlin.duan42@gmail.com
2024.05.09
"""
############################# modules #########################################
import matplotlib
import msprime
import pandas
import tskit
import pyslim
import matplotlib
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.spatial import distance_matrix
import numpy as np
import random
from time import time
import sys # for sys.exit()
import allel # for allel.weir_cockerham_fst()
import glob #for loading files
from collections import Counter
import pandas #dataframe
import os #mkdir
# matplotlib.use("qt5agg") # Not work
import matplotlib.pyplot as plt
import scipy.stats as stats
import sys # for sys.exit()
import allel # for allel.weir_cockerham_fst()
import matplotlib.patches as mpatches # manually make legends
import seaborn as sns

############################# options #############################
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-i', '--input',
                    help='Path the the input tables',
                    type=str)
# parser.add_argument('-n', '--name',
#                     help='Short model name',
#                     type=str)
# parser.add_argument('-p', '--plot',
#                     help='1 for generating plots and 0 for not plotting',
#                     type=int, default=1)
args = parser.parse_args()

############################# program #########################################
# Values
# sigma_w = 0.4
# dist_mate = 0.12
num_runs = 100
inPath = args.input


# short_model_name = "m2b_highPoly_lowMig_clineMap"
# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/Continuous_nonWF_M2b_glacialHistory_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12/tick101000/"

# short_model_name = "m2b_highPoly_lowMig_clineMap"
# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/Continuous_nonWF_M2b_glacialHistory_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12/tick110000/"

# short_model_name = "m2b_highPoly_lowMig_clineMap"
# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/Continuous_nonWF_M2b_glacialHistory_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12/tick110000/"


# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/historical_optimum_0/Continuous_nonWF_M2b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12/tick101000/"
# short_model_name = args.name
short_model_name = inPath.split("/")[-3]

figPath = ("/home/tianlin/Documents/github/data/tskit_data/figure/20240516/" +
           short_model_name + "/100runs_" + inPath.split("/")[-2]+"/")
outPath = ("/home/tianlin/Documents/github/data/tskit_data/output/multiple_runs/" +
           short_model_name + "/100runs_" + inPath.split("/")[-2]+"/")
if not os.path.exists(outPath):
    os.makedirs(outPath)
if not os.path.exists(figPath):
    os.makedirs(figPath)

# Check this before use!
model_name = "_".join(inPath.split("/")[-3:-1] + ["100runs"])
tick = int(inPath.split("/")[-2].split("tick")[-1])
event_age = tick - 100000

# Shape of the table:
# dataTable[0]     mutation ID
# dataTable[1]     age,
# dataTable[2]     freq,
# dataTable[3]     mut_effect,
# dataTable[4]     delta_LF_mut,
# dataTable[5]     cor_GE[0]: Kandell's tau
# dataTable[6]     cor_GE[1]: p-value
# dataTable[7]     relative to the sum of positive delta_LF_mut (delta_LF_mut/sum of positive LF_mut )
# dataTable[8]     relative to sum of delta_LF_mut (delta_LF_mut/sum of LF_mut )
# dataTable[9]     temperary run ID 0,1,2...(number of files-1)
# dataTable[10]    rank of p-values
dataTable = np.empty((11, 0))
# Load results of multiple runs from file
fileList = glob.glob(inPath + "*.txt")
run = 0
lf_sums = []
for f in fileList:
    focalTable = np.loadtxt(f)
    # print(np.shape(focalTable))
    # Add relative positive delta_LF_mut (delta_LF_mut/sum of positive LF_mut)
    relative_positive_lf_mut = focalTable[4]/sum(focalTable[4][focalTable[4]>0])
    lf_sum = sum(focalTable[4])
    lf_sums.append(lf_sum)
    relative_lf_mut = focalTable[4] / sum(focalTable[4])
    p_rank = focalTable[6].argsort().argsort()
    # print(len(focalTable[0]))
    # Add relative delta_LF_mut ,temporary run ID, and rank of p-values
    focalTable = np.concatenate((focalTable,
                                 [relative_positive_lf_mut],
                                 [relative_lf_mut],
                                 np.full(shape=(1, len(focalTable[0])),
                                         fill_value=run),
                                 [p_rank]),
                                axis=0)
    dataTable = np.concatenate((dataTable, focalTable), axis=1)
    run += 1

# Change to pandas dadaframe
dataTable_t = dataTable.transpose()
df = pandas.DataFrame(data=dataTable_t,
                      columns=["id", "age", "freq",
                               "mut_effect","delta_LF_mut","tau",
                               "p", "relative_positive_lf", "relative_lf",
                               "run_id", "p_rank"])

# True positive rate, False negative rate, False discovery rate
# True adaptive allele: account for more than LF_min percent of positve LF_mut
# GEA significant: BH-adjusted p-value < 0.05
LF_min = 0.01
num_cat = 20
cat_width = int(100/num_cat) if 100 % num_cat == 0 else 100/num_cat
age_percentile = np.percentile(dataTable[1],
                               np.append(np.arange(0, 100, cat_width),
                                         100))
event_percentile = stats.percentileofscore(dataTable[1], event_age)
TPR = []
FPR = []
FDR = []
for i in range(num_cat):
    focal_age = np.logical_and(dataTable[1] > age_percentile[i],
                               dataTable[1] <= age_percentile[i+1])
    dataTable_category = dataTable[:, focal_age]
    # num_allele = len(p_BH_category)
    # proportion_sig.append(sum(p_BH_category < 0.05)/num_allele)
    expP = dataTable_category[7] > LF_min
    obsP = dataTable_category[6] < 0.05
    TP = sum(expP & obsP)
    FP = sum(~expP & obsP)
    FN = sum(expP & ~obsP)
    TN = sum(~expP & ~obsP)
    TPR.append(TP/(TP+FN))
    FPR.append(FP/(TN+FP))
    FDR.append(FP/(TP+FP))



# Plots
# Relative LF_mut ~ cor_GE p-values RANKS, colored by age rank bins
p_rank = df["p_rank"]
age_rank_bin = (dataTable[1].argsort().argsort()/10000).astype(int)
plt.scatter(p_rank, dataTable[7],
         marker="o",
         c=age_rank_bin, alpha=0.05)
plt.xlabel("GEA p-values ranks")
plt.ylabel("Relative $LF_{mut}$")
plt.colorbar().set_label("Age rank bins \n (10000 alleles per bin)")
plt.tight_layout()
plt.savefig(figPath+model_name+"_corGEpvalueRank_vs_relativeLFmut_ageBinColor2.png",
            dpi=300)
plt.close()

# # Histogram sby allele age bins
# # Relative LF_mut ~ cor_GE p-values RANKS
# num_cat = 20
# age_percentile = np.percentile(dataTable[1],
#                                np.append(np.arange(0, 100, 100/num_cat),
#                                          100))
# lf_min = min(dataTable[7])
# lf_max = max(dataTable[7])
# for i in range(num_cat):
#     p_category = dataTable[6][np.logical_and(dataTable[1] > age_percentile[i],
#                                           dataTable[1] <= age_percentile[i+1])]
#     p_category_rank = p_category.argsort().argsort()
#     relative_LF_mut = dataTable[7][
#         np.logical_and(dataTable[1] > age_percentile[i],
#                        dataTable[1] <= age_percentile[i + 1])
#     ]
#     num_allele = len(p_category)
#     # proportion_sig.append(sum(p_category < 0.05) / num_allele)
#     plt.scatter(p_category_rank, relative_LF_mut,
#                 marker="o",
#                 c="grey", alpha=0.2)
#     plt.ylim(lf_min*1.10, lf_max*1.05)
#     plt.xlabel("GEA p-values ranks")
#     plt.ylabel("Relative $LF_{mut}$")
#     plt.title("Rank bin" + str(i) + ": \n " +
#               "age " +str(int(age_percentile[i])) +
#               "-" + str(int(age_percentile[i+1])))
#     plt.tight_layout()
#     plt.savefig(figPath + model_name + "AgeBin" + str(i) +
#                 "_corGEpvalueRank_vs_relativeLFmut.png",
#                 dpi=300)
#     plt.close()


num_cat = 20
# TPR ～ Allele age
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat),
plt.plot(np.arange(0, num_cat, 1),
         TPR,
         color="grey")
# Event start
plt.axvline(num_cat*event_percentile/100,
            color='firebrick', lw=1, dashes=(2,1))
plt.xlabel("Allele age percentile bins")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("True positive rate (TP/(TP+FN))")
# plt.xticks(ticks=np.arange(100/num_cat, 101, 100/num_cat),
#            labels=[(str(i*cat_width)+"-"+str((i+1)*cat_width))
#                    for i in range(num_cat)])
plt.xticks(ticks=np.arange(0, num_cat, 1),
           labels=[str(i)
                   for i in range(num_cat)])
plt.tick_params(axis='x', rotation=45)
# plt.savefig(figPath+model_name+"_proportionGEABHp_vs_age.png",
#             dpi=300)
plt.tight_layout()
plt.savefig(figPath+model_name+str(num_cat)+"_minLF"+str(LF_min)+"_"+
            str(num_cat)+"bins"+"_TPR_lfmut1percent_GEABHp0.05_vs_age.png",
            dpi=300)
plt.close()

# FPR ～ Allele age
# plt.plot(np.arange(100/num_cat, 101, 100/num_cat),
plt.plot(np.arange(0, num_cat, 1),
         FPR,
         color="grey")
# Event start
plt.axvline(num_cat*event_percentile/100,
            color='firebrick', lw=1, dashes=(2,1))
plt.xlabel("Allele age percentile bins")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate (FP/(FP+TN)))")
# plt.xticks(ticks=np.arange(100/num_cat, 101, 100/num_cat),
#            labels=[(str(i*cat_width)+"-"+str((i+1)*cat_width))
#                    for i in range(num_cat)])
plt.xticks(ticks=np.arange(0, num_cat, 1),
           labels=[str(i)
                   for i in range(num_cat)])
plt.tick_params(axis='x', rotation=45)
# plt.savefig(figPath+model_name+"_proportionGEABHp_vs_age.png",
#             dpi=300)
plt.tight_layout()
plt.savefig(figPath+model_name+str(num_cat)+"_minLF"+str(LF_min)+"_"+
            str(num_cat)+"bins"+"_FPR_lfmut1percent_GEABHp0.05_vs_age.png",
            dpi=300)
plt.close()


# FDR ～ Allele age
plt.plot(np.arange(0, num_cat, 1),
# plt.plot(np.arange(50/num_cat, 101, 100/num_cat),
         FDR,
         color="grey")
# Event start
plt.axvline(num_cat*event_percentile/100,
            color='firebrick', lw=1, dashes=(2,1))
# plt.xlabel("Allele age percentile bins")
plt.xlabel("Allele age rank bins")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False discovery rate (FP/(FP+TP)))")
# plt.xticks(ticks=np.arange(0, 101, 100/num_cat),
# labels=[str(i*cat_width)
#         for i in range(num_cat)])
plt.xticks(ticks=np.arange(0, num_cat, 1),
           labels=[str(i)
                   for i in range(num_cat)])
plt.tick_params(axis='x', rotation=45)
# plt.savefig(figPath+model_name+"_proportionGEABHp_vs_age.png",
#             dpi=300)
plt.tight_layout()
plt.savefig(figPath+model_name+str(num_cat)+"_minLF"+str(LF_min)+"_"+
            str(num_cat)+"bins"+"_FDR_lfmut1percent_GEABHp0.05_vs_age.png",
            dpi=300)
plt.close()


#### Cumulative plot of LF_mut ####
expected_explained_proportion = 0.8
num_mut_runs = Counter(dataTable[9]).values()

cumulative_lf_list = []
gea_goal = []
explained = []
for i in range(100):
    # print(i)
    focal_relative_lf_mut = dataTable[7][dataTable[9] == i]
    relative_positive_lf_mut = focal_relative_lf_mut[focal_relative_lf_mut > 0]
    sorted_lfmut = np.array(list(reversed(sorted(relative_positive_lf_mut))))
    # Trim the tails with near-0 contributions to ensure all runs have the same
    # number of mutations
    #sorted_lfmut = sorted_lfmut[0:minimum_muts-1]
    # positiveTotal = sum(sorted_lfmut)
    focal_cumulative_lf = [0] + [sum(sorted_lfmut[0:k+1])
                                 for k in range(len(sorted_lfmut))]
    # How many alleles do we need to account for 80% of current local adaptation?
    focal_gea_goal = sum(np.array(focal_cumulative_lf) < expected_explained_proportion)
    focal_explained = focal_cumulative_lf[focal_gea_goal]
    cumulative_lf_list.append(focal_cumulative_lf)
    gea_goal.append(focal_gea_goal)
    explained.append(focal_explained)

# Convert the "list of lists" to a numpy array by adding np.nan values to the end
max_num_positive_mut = len(max(cumulative_lf_list, key=len))
cumulative_lf = np.full(shape=(run, max_num_positive_mut), fill_value=np.nan)
for i in range(run):
    n = len(cumulative_lf_list[i])
    cumulative_lf[i][0:n] = cumulative_lf_list[i]

# mean_cumulative_lf = np.mean(cumulative_lf, axis=0)
# median_cumulative_lf = np.median(cumulative_lf, axis=0)
# mean_trim_len = np.count_nonzero(~np.isnan(mean_cumulative_lf))
# median_trim_len = np.count_nonzero(~np.isnan(median_cumulative_lf))

# Calculate mean and meadian and ignore np.nan values
mean_cumulative_lf = np.nanmean(cumulative_lf, axis=0)
median_cumulative_lf = np.nanmedian(cumulative_lf, axis=0)
mean_gea_goal = int(np.mean(gea_goal))
mean_explained = mean_cumulative_lf[mean_gea_goal]
median_gea_goal = int(np.mean(gea_goal))
median_explained = median_cumulative_lf[median_gea_goal]

# # Plot cumulative_lf: Mean with range
# for i in range(run):
#     y = np.array(cumulative_lf_list[i])
#     x = range(len(y))
#     plt.plot(x, y,
#              color="lightseagreen", alpha = 0.05)
# plt.plot(range(len(mean_cumulative_lf)), mean_cumulative_lf,
#              color="black")
# plt.xlabel("Mutations sorted in descending order of $LF_{mut}$")
# plt.ylabel("Cumulative proportion of positive LF")
#     # plt.axvline(x=mean_gea_goal, color="firebrick", linestyle="dotted")
#     # plt.axhline(y=mean_explained, color="firebrick", linestyle="dotted")
#
# plt.plot([mean_gea_goal, mean_gea_goal], [0, mean_explained],
#          color="firebrick", linestyle="dotted")
# plt.plot([0, mean_gea_goal], [mean_explained, mean_explained],
#          color="firebrick", linestyle="dotted")
# plt.annotate(str(mean_gea_goal), xy=(mean_gea_goal+1, mean_explained),
#              xytext=(mean_gea_goal + 1 + len(mean_cumulative_lf)/40, 0),
#              color="firebrick")
# plt.savefig(figPath + model_name +
#             "_meanLFcumulative_positive_100runs_meanAndRange.png",
#             dpi=300)
# plt.close()

# Plot cumulative_lf: Median with range
for i in range(run):
    y = np.array(cumulative_lf_list[i])
    x = range(len(y))
    plt.plot(x, y,
             color="lightseagreen", alpha = 0.05)
plt.plot(range(len(median_cumulative_lf)), median_cumulative_lf,
             color="black")
plt.xlabel("Mutations sorted in descending order of $LF_{mut}$")
plt.ylabel("Cumulative proportion of positive LF")
plt.plot([median_gea_goal, median_gea_goal], [0, median_explained],
         color="firebrick", linestyle="dotted")
plt.plot([0, median_gea_goal], [median_explained, median_explained],
         color="firebrick", linestyle="dotted")
plt.annotate(str(median_gea_goal), xy=(median_gea_goal+1, median_explained),
             xytext=(median_gea_goal + 1 + len(median_cumulative_lf)/40, 0),
             color="firebrick")
plt.savefig(figPath + model_name +
            "_medianLFcumulative_positive_100runs_medianAndRange.png",
            dpi=300)
plt.close()



# Sum of LF of the size class ~ |phenotypic effect size|
# Sum of LF of the size class ~ |phenotypic effect size|, separating positive and negative parts
# # Methods 1: runs combined
# num_cat = 20 # Number of categories for allele age
# abs_effect = abs(df["mut_effect"])
# LF_total = sum(df["delta_LF_mut"])
# # LF_positive = sum(df["delta_LF_mut"][df["delta_LF_mut"] > 0])
# # LF_negative = sum(df["delta_LF_mut"][df["delta_LF_mut"] < 0])
# lf_sum = []
# lf_sum_positive = []
# lf_sum_negative = []
# alpha_cats = np.append(np.arange(0, max(abs_effect), max(abs_effect)/num_cat),
#                        max(abs_effect))
# for i in range(num_cat):
#     lf_category = df["delta_LF_mut"][np.logical_and(abs_effect > alpha_cats[i],
#                                               abs_effect <= alpha_cats[i+1])]
#     lf_sum.append(sum(lf_category/LF_total))
#     lf_sum_positive.append(sum(lf_category[lf_category > 0]) / LF_total)
#     lf_sum_negative.append(sum(lf_category[lf_category < 0]) / LF_total)
#
# #total LF of the size ~ |phenotypic effect size|
# plt.figure(1)
# plt.plot(alpha_cats[1:],
#          lf_sum,
#          color="grey")
# plt.xlabel("|Mutation phenotypic effect size|")
# plt.ylabel("Relative contribution to local adaptation from the size class")
# # plt.xticks(ticks=np.arange(100/num_cat, 101, 100/num_cat),
# #            labels=[(str(i*cat_width)+"-"+str((i+1)*cat_width))
# #                    for i in range(num_cat)])
# plt.tight_layout()
# plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
#             "_LF_by_absEffectSize_bin.png",
#             dpi=300)
# plt.close()
#
# # total LF of the size ~ |phenotypic effect size|, separated by positive and
# # negative contributions
# plt.figure(1)
# lf_sum_positive = np.array(lf_sum_positive)
# lf_sum_negative = np.array(lf_sum_negative)
# x = alpha_cats[1:]
# y1 = lf_sum_positive
# y2 = lf_sum_negative
# fig, ax = plt.subplots()
# ax.plot(x, y1, color="mediumaquamarine",
#         label="Positive")
# ax.plot(x, y2, color="saddlebrown",
#         label="Negative")
# ax.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.xlabel("|Mutation phenotypic effect size|")
# plt.ylabel("Relative contribution to local adaptation from the size class")
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
# plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins" +
#             "_LF_by_absEffectSize_bin_positveAndnegative.png",
#             dpi=300)
# plt.close()

# Methods 2: relative to the total LF of each run
num_cat = 20 # Number of categories for phenotypic effect
abs_effect = abs(df["mut_effect"])
lf_sum = []
lf_sum_positive = []
lf_sum_negative = []
alpha_cats = np.append(np.arange(0, max(abs_effect), max(abs_effect)/num_cat),
                       max(abs_effect))
for i in range(num_cat):
    lf_category = df["relative_lf"][np.logical_and(abs_effect > alpha_cats[i],
                                              abs_effect <= alpha_cats[i+1])]
    lf_sum.append(sum(lf_category)/num_runs)
    lf_sum_positive.append(sum(lf_category[lf_category > 0])/num_runs)
    lf_sum_negative.append(sum(lf_category[lf_category < 0])/num_runs)

# total LF of the size ~ |phenotypic effect size|, separated by positive and
# negative contributions
# # line plot: Not used
# plt.figure(1)
# lf_sum_positive = np.array(lf_sum_positive)
# lf_sum_negative = np.array(lf_sum_negative)
# x = alpha_cats[1:]
# y1 = lf_sum_positive
# y2 = lf_sum_negative
# fig, ax = plt.subplots()
# ax.plot(x, y1, color="mediumaquamarine",
#         label="Positive")
# ax.plot(x, y2, color="saddlebrown",
#         label="Negative")
# ax.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.xlabel("|Mutation phenotypic effect size|")
# plt.ylabel("Relative contribution to local adaptation from the size class")
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
# plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
#             "_LF_by_absEffectSize_bin_positveAndnegative_lfRelative2EachRun.png",
#             dpi=300)
# plt.close()

# barplot
plt.figure(1)
lf_sum_positive = np.array(lf_sum_positive)
lf_sum_negative = np.array(lf_sum_negative)
x = alpha_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
fig, ax = plt.subplots()
# bar_width = 0.002 # High polygenicity
bar_width = 0.016 # High polygenicity
ax.bar(x, y1, color="mediumaquamarine",
        label="Positive",
       width=bar_width)
ax.bar(x, y2, color="saddlebrown",
        label="Negative",
       width=bar_width)
ax.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.xlabel("|Mutation phenotypic effect size|")
plt.ylabel("Total relative contribution to local adaptation" +
           "\n" + "from the size class")
# plt.xlim(0, 0.05) # High polygenicity
plt.xlim(0, 0.40) # Low polygenicity
plt.ylim(-0.08, 0.2)
ax.legend(loc="upper right")
ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
ax.margins(x=0)
plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
            "_LF_by_absEffectSize_bin_positveAndnegative_lfRelative2EachRun_barPlot.png",
            dpi=300)
plt.close()



# Sum of LF from the age class ~ Allele age
num_cat = 25 # Number of categories for allele age
# lf_sum = []
lf_sum_positive = []
lf_sum_negative = []
age = np.log10(df["age"])
# age = df["age"]
age_cats = np.append(np.arange(0, max(age), max(age)/num_cat),
                     max(age))
for i in range(num_cat):
    lf_category = df["relative_lf"][np.logical_and(age > age_cats[i],
                                              age <= age_cats[i+1])]
    lf_sum.append(sum(lf_category)/num_runs)
    lf_sum_positive.append(sum(lf_category[lf_category > 0])/num_runs)
    lf_sum_negative.append(sum(lf_category[lf_category < 0])/num_runs)

# total LF of the age class ~ allele age, separated by positive and
# negative contributions
# # line plot: Not used
# plt.figure(1)
# lf_sum_positive = np.array(lf_sum_positive)
# lf_sum_negative = np.array(lf_sum_negative)
# x = age_cats[1:]
# y1 = lf_sum_positive
# y2 = lf_sum_negative
# fig, ax = plt.subplots()
# ax.plot(x, y1, color="mediumaquamarine",
#         label="Positive")
# ax.plot(x, y2, color="saddlebrown",
#         label="Negative")
# ax.axhline(0, color='grey', lw=1, dashes=(1,1))
# ax.axvline(np.log10(event_tick), color='firebrick', lw=1, dashes=(2,1))
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in 10**np.arange(0, max(x), 1)])
# plt.tick_params(axis='x', rotation=45)
# plt.xlabel("Allele age (generation)")
# plt.ylabel("Total relative contribution to local adaptation" +
#            "\n" + "from the age class")
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
# plt.tight_layout()
# plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
#             "_LF_by_age_bin_positveAndnegative_lfRelative2EachRun.png",
#             dpi=300)
# plt.close()

# bar plot
plt.figure(1)
lf_sum_positive = np.array(lf_sum_positive)
lf_sum_negative = np.array(lf_sum_negative)
x = age_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
plt.bar(x, y1, color="mediumaquamarine",
       label="Positive",
       width=0.18)
plt.bar(x, y2, color="saddlebrown",
       label="Negative",
       width=0.18)
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.axvline(np.log10(event_age), color='firebrick', lw=1, dashes=(2,1))
plt.xticks(ticks=np.arange(0, max(x), 1),
           labels=['{:0.2e}'.format(i)
                   for i in 10**np.arange(0, max(x), 1)])
plt.tick_params(axis='x', rotation=45)
plt.xlabel("Allele age (generation)")
plt.ylabel("Total relative contribution to local adaptation" +
           "\n" + "from the age class")
ax.legend(loc="upper right")
ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
            "_LF_by_log10age_bin_positveAndnegative_lfRelative2EachRun.png",
            dpi=300)
plt.close()



# Contribute to local adaptation by frequency bins
# Sum of LF from the age class ~ Allele age
num_cat = 25 # Number of categories for allele age
# lf_sum = []
lf_sum_positive = []
lf_sum_negative = []
freq = df["freq"]
freq_cats = np.append(np.arange(0, 1, 1.0/num_cat),
                     1)
for i in range(num_cat):
    lf_category = df["relative_lf"][np.logical_and(freq > freq_cats[i],
                                              freq <= freq_cats[i+1])]
    lf_sum.append(sum(lf_category)/num_runs)
    lf_sum_positive.append(sum(lf_category[lf_category > 0])/num_runs)
    lf_sum_negative.append(sum(lf_category[lf_category < 0])/num_runs)

# bar plot
# plt.figure(1)
lf_sum_positive = np.array(lf_sum_positive)
lf_sum_negative = np.array(lf_sum_negative)
x = freq_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
plt.bar(x, y1, color="mediumaquamarine",
       label="Positive",
       width=0.035)
plt.bar(x, y2, color="saddlebrown",
       label="Negative",
       width=0.035)
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in 10**np.arange(0, max(x), 1)])
# plt.tick_params(axis='x', rotation=45)
plt.xlabel("Frequency")
plt.ylabel("Total relative contribution to local adaptation" +
           "\n" + "from the frequency class")
ax.legend(loc="upper right")
ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
            "_LF_by_log10freq_bin_positveAndnegative_lfRelative2EachRun.png",
            dpi=300)
plt.close()



# Three way relationship among allele freq, effect size and contribution to LF
df_polymorphic = df[(df["freq"] != 1) & (df["freq"] != 0)]
max_lf = max(df_polymorphic["delta_LF_mut"])
min_lf = min(df_polymorphic["delta_LF_mut"])
# plt.scatter(abs(df_polymorphic["mut_effect"]), df_polymorphic["delta_LF_mut"],
#             marker="o", c=df_polymorphic["freq"], alpha=0.1, s=20)
# plt.xlabel("|Mutation phenotypic effect size|")
# plt.ylabel("$LF_{mut}$")
# plt.colorbar().set_label("Allele Frequency")
# plt.tight_layout()
# plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_frequencyColor.png",
#             dpi=300)
# plt.close()

# Use minor allele frequency
minor_freq = []
for f in df_polymorphic["freq"]:
    if f <= 0.5:
        minor_freq.append(f)
    else:
        minor_freq.append(1-f)
minor_freq = np.array(minor_freq)

plt.scatter(abs(df_polymorphic["mut_effect"]), df_polymorphic["delta_LF_mut"],
            marker="o", c=minor_freq,
            alpha=0.1, s=20)
plt.xlabel("|Mutation phenotypic effect size|")
plt.ylabel("$LF_{mut}$")
plt.xlim(left=0,
         right=0.05)
plt.ylim(bottom=-0.004, top=0.016)
plt.colorbar().set_label("Minor allele Frequency")
plt.tight_layout()
plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_minorFrequencyColor.png",
            dpi=300)
plt.close()

# Separated by high and low frequencies
# df_middleFreq = df_polymorphic[(df_polymorphic["freq"] >= 0.25) &
#                                (df_polymorphic["freq"] < 0.75)]
# df_lowHighFreq = df_polymorphic[(df_polymorphic["freq"] >= 0.75) |
#                                 (df_polymorphic["freq"] < 0.25)]

# plt.scatter(abs(df_middleFreq["mut_effect"]),
#             df_middleFreq["delta_LF_mut"],
#             marker="o", c=df_middleFreq["freq"],
#             alpha=0.1, s=20,
#             vmin=0, vmax=1)
# plt.xlabel("|Mutation phenotypic effect size|")
# plt.ylabel("$LF_{mut}$")
# plt.xlim(left=min(abs(df_polymorphic["mut_effect"])),
#          right=max(abs(df_polymorphic["mut_effect"])))
# plt.ylim(bottom=min_lf, top=max_lf)
# plt.colorbar().set_label("Allele Frequency")
# plt.tight_layout()
# plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_frequencyColor_middleFreq.png",
#             dpi=300)
# plt.close()
#
# plt.scatter(abs(df_lowHighFreq["mut_effect"]),
#             df_lowHighFreq["delta_LF_mut"],
#             marker="o", c=df_lowHighFreq["freq"],
#             alpha=0.1, s=20,
#             vmin=0, vmax=1)
# plt.xlabel("|Mutation phenotypic effect size|")
# plt.ylabel("$LF_{mut}$")
# plt.xlim(left=min(abs(df_polymorphic["mut_effect"])),
#          right=max(abs(df_polymorphic["mut_effect"])))
# plt.ylim(bottom=min_lf, top=max_lf)
# plt.colorbar().set_label("Allele Frequency")
# plt.tight_layout()
# plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_frequencyColor_lowHighFreq.png",
#             dpi=300)
# plt.close()

#Minor allele frequency: separate 0-0.25, 0.25-0.5
df_middleFreq = df_polymorphic[minor_freq >= 0.25]
df_lowHighFreq = df_polymorphic[minor_freq < 0.25]
plt.scatter(abs(df_middleFreq["mut_effect"]),
            df_middleFreq["delta_LF_mut"],
            marker="o", c=minor_freq[minor_freq >= 0.25],
            alpha=0.1, s=20,
            vmin=0, vmax=0.5)
plt.xlabel("|Mutation phenotypic effect size|")
plt.ylabel("$LF_{mut}$")
plt.xlim(left=0,
         right=0.05)
plt.ylim(bottom=-0.004, top=0.016)
plt.colorbar().set_label("Minor allele Frequency")
plt.tight_layout()
plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_frequencyColor_highMinorFreq.png",
            dpi=300)
plt.close()

plt.scatter(abs(df_lowHighFreq["mut_effect"]),
            df_lowHighFreq["delta_LF_mut"],
            marker="o", c=minor_freq[minor_freq < 0.25],
            alpha=0.1, s=20,
            vmin=0, vmax=0.5)
plt.xlabel("|Mutation phenotypic effect size|")
plt.ylabel("$LF_{mut}$")
plt.xlim(left=0,
         right=0.05)
plt.ylim(bottom=-0.004, top=0.016)
plt.colorbar().set_label("Minor allele Frequency")
plt.tight_layout()
plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_frequencyColor_lowMinorFreq.png",
            dpi=300)
plt.close()


#Three way relationship 1
# Sum of LF from the age class ~ Allele age Colored by |effect size|
num_age_cat = 25 # Number of categories for allele age
num_size_cat = 5 # Number of categories for allele age
# lf_sum = []
lf_sum_positive = np.full(shape=(5, 25), fill_value=np.nan)
lf_sum_negative = np.full(shape=(5, 25), fill_value=np.nan)
age = np.log10(df["age"])
size = df["mut_effect"]
# age = df["age"]
age_cats = np.append(np.arange(0, max(age), max(age)/num_age_cat),
                     max(age))
size_cats = np.array([0, 0.01, 0.02, 0.03, 0.04, max(df["mut_effect"])]) # Hard coded
for i in range(num_age_cat):
    for j in range(num_size_cat):
        focal_range = np.logical_and(np.logical_and(age > age_cats[i],
                                                    age <= age_cats[i + 1]),
                                     np.logical_and(abs(size) > size_cats[j],
                                                    abs(size) <= size_cats[j + 1]))
        lf_category = df["relative_lf"][focal_range]
        lf_sum_positive[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
        lf_sum_negative[j][i] = (sum(lf_category[lf_category < 0])/num_runs)

# bar plot
plt.figure(1)
x = age_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
colors = ["#FDE257FF", "#95D840FF", "#29AF7FFF","#287D8EFF","#440154FF"]
patch1 = mpatches.Patch(color=colors[0], label='0-0.01')
patch2 = mpatches.Patch(color=colors[1], label='0.01-0.02')
patch3 = mpatches.Patch(color=colors[2], label='0.02-0.03')
patch4 = mpatches.Patch(color=colors[3], label='0.03-0.04')
patch5 = mpatches.Patch(color=colors[4], label='> 0.04')
# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.zeros(num_age_cat)
bar_width = 0.2
for row in range(num_size_cat):
    plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + lf_sum_positive[row]
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.axvline(np.log10(event_age), color='firebrick', lw=1, dashes=(2,1))
plt.xticks(ticks=np.arange(0, max(x), 1),
           labels=['{:0.2e}'.format(i)
                   for i in 10**np.arange(0, max(x), 1)])
plt.tick_params(axis='x', rotation=45)
plt.xlabel("Allele age (generation)")
plt.ylabel("Total relative contribution to local adaptation" +
           "\n" + "from the age class")
plt.legend(handles=[patch5, patch4, patch3, patch2, patch1],
           title="|Mutation phenotypic effect size|",
           loc="upper left")
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_age_cat) + "bins"+
            "_LF_by_log10age_bin_positve_lfRelative2EachRun_sizeColor.png",
            dpi=300)
plt.close()



#Three-way relationship 2
# Sum of LF from the age class ~ Allele age, Colored by frequency
num_age_cat = 25 # Number of categories for allele age
num_freq_cat = 10 # Number of categories for allele frequency
# lf_sum = []
lf_sum_positive = np.full(shape=(10, 25), fill_value=np.nan)
lf_sum_negative = np.full(shape=(10, 25), fill_value=np.nan)
age = np.log10(df["age"])
freq = df["freq"]
# age = df["age"]
age_cats = np.append(np.arange(0, max(age), max(age)/num_age_cat),
                     max(age))
freq_cats = np.arange(0,1.1, 0.1) # Hard coded
for i in range(num_age_cat):
    for j in range(num_freq_cat):
        focal_range = np.logical_and(np.logical_and(age > age_cats[i],
                                                    age <= age_cats[i + 1]),
                                     np.logical_and(freq > freq_cats[j],
                                                    freq <= freq_cats[j + 1]))
        lf_category = df["relative_lf"][focal_range]
        lf_sum_positive[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
        lf_sum_negative[j][i] = (sum(lf_category[lf_category < 0])/num_runs)

# bar plot
plt.figure(1)
x = age_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
# colors = ["#f2e5f9FF", "#dbcee9FF", "#b9a1d3FF", "#9B7DC5FF", "#7757adFF",
#           "#623f9cFF", "#51308cFF", "#3c1e7aFF", "#2c0f70FF", "#200462FF"]
colors = ["#d2ebf3FF", "#9dcde3FF", "#6899CEFF", "#4074cbFF", "#1839aaFF",
          "#1624a1FF", "#523cb7FF", "#8f69caFF", "#c2a0dfFF", "#e5d0f0FF"]
patch1 = mpatches.Patch(color=colors[0], label='0-0.1')
patch2 = mpatches.Patch(color=colors[1], label='0.1-0.2')
patch3 = mpatches.Patch(color=colors[2], label='0.2-0.3')
patch4 = mpatches.Patch(color=colors[3], label='0.3-0.4')
patch5 = mpatches.Patch(color=colors[4], label='0.4-0.5')
patch6 = mpatches.Patch(color=colors[5], label='0.5-0.6')
patch7 = mpatches.Patch(color=colors[6], label='0.6-0.7')
patch8 = mpatches.Patch(color=colors[7], label='0.7-0.8')
patch9 = mpatches.Patch(color=colors[8], label='0.8-0.9')
patch10 = mpatches.Patch(color=colors[9], label='0.9-1.0')

# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.zeros(num_age_cat)
bar_width = 0.2
for row in range(num_freq_cat):
    plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + lf_sum_positive[row]
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.axvline(np.log10(event_age), color='firebrick', lw=1, dashes=(2,1))
plt.xticks(ticks=np.arange(0, max(x), 1),
           labels=['{:0.2e}'.format(i)
                   for i in 10**np.arange(0, max(x), 1)])
plt.tick_params(axis='x', rotation=45)
plt.xlabel("Allele age (generation)")
plt.ylabel("Total relative contribution to local adaptation" +
           "\n" + "from the age class")
plt.legend(handles=[patch10, patch9, patch8, patch7, patch6,
                    patch5, patch4, patch3, patch2, patch1],
           title="Allele frequency",
           loc="upper left")
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_age_cat) + "bins"+
            "_LF_by_log10age_bin_positve_lfRelative2EachRun_freqColor.png",
            dpi=300)
plt.close()


#Three-way relationship 3
# Sum of LF from the size class ~ Effect size, Colored by frequency
abs_size = abs(df["mut_effect"])
num_size_cat = 20 # Number of categories for phenotypic effect
num_freq_cat = 10 # Number of categories for allele frequency
lf_sum_positive = np.full(shape=(10, 20), fill_value=np.nan)
lf_sum_negative = np.full(shape=(10, 20), fill_value=np.nan)
size_cats = np.append(np.arange(0, max(abs_size), max(abs_size)/num_size_cat),
                       max(abs_size))
freq_cats = np.arange(0,1.1, 0.1) # Hard coded
for i in range(num_size_cat):
    for j in range(num_freq_cat):
        focal_range = np.logical_and(np.logical_and(abs_size > size_cats[i],
                                                    abs_size <= size_cats[i + 1]),
                                     np.logical_and(freq > freq_cats[j],
                                                    freq <= freq_cats[j + 1]))
        lf_category = df["relative_lf"][focal_range]
        lf_sum_positive[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
        lf_sum_negative[j][i] = (sum(lf_category[lf_category < 0])/num_runs)

# bar plot
plt.figure(1)
x = size_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
# colors = ["#f2e5f9FF", "#dbcee9FF", "#b9a1d3FF", "#9B7DC5FF", "#7757adFF",
#           "#623f9cFF", "#51308cFF", "#3c1e7aFF", "#2c0f70FF", "#200462FF"]
colors = ["#d2ebf3FF", "#9dcde3FF", "#6899CEFF", "#4074cbFF", "#1839aaFF",
          "#1624a1FF", "#523cb7FF", "#8f69caFF", "#c2a0dfFF", "#e5d0f0FF"]
patch1 = mpatches.Patch(color=colors[0], label='0-0.1')
patch2 = mpatches.Patch(color=colors[1], label='0.1-0.2')
patch3 = mpatches.Patch(color=colors[2], label='0.2-0.3')
patch4 = mpatches.Patch(color=colors[3], label='0.3-0.4')
patch5 = mpatches.Patch(color=colors[4], label='0.4-0.5')
patch6 = mpatches.Patch(color=colors[5], label='0.5-0.6')
patch7 = mpatches.Patch(color=colors[6], label='0.6-0.7')
patch8 = mpatches.Patch(color=colors[7], label='0.7-0.8')
patch9 = mpatches.Patch(color=colors[8], label='0.8-0.9')
patch10 = mpatches.Patch(color=colors[9], label='0.9-1.0')

# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.zeros(num_size_cat)
# bar_width = 0.002 # High polygenicity
bar_width = 0.016 # Low polygenicity
for row in range(num_freq_cat):
    plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + lf_sum_positive[row]
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.axvline(np.log10(event_age), color='firebrick', lw=1, dashes=(2,1))
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in np.arange(0, max(x), 0.005)])
plt.tick_params(axis='x', rotation=45)
plt.xlabel("|Mutation phenotypic effect size|")
plt.ylabel("Total relative contribution to local adaptation" +
           "\n" + "from the size class")
plt.legend(handles=[patch10, patch9, patch8, patch7, patch6,
                    patch5, patch4, patch3, patch2, patch1],
           title="Allele frequency",
           loc="upper right")
# plt.xlim(0, 0.05) # High polygenicity
plt.xlim(0, 0.40) # Low polygenicity
plt.ylim(0, 0.2)
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_size_cat) + "bins"+
            "_LF_by_size_bin_positve_lfRelative2EachRun_freqColor.png",
            dpi=300)
plt.close()


# GEA results ~ Allele age for neutral alleles
# len(df["mut_effect"])
# sum(df["mut_effect"] == 0)
plt.scatter(np.log10(df["age"]),
            abs(df["tau"]),
            marker="o",
            # c=df["freq"],
            c="grey",
            alpha=0.01, s=10,
            vmin=0, vmax=0.5)
plt.xlabel("log10(Allele age)")
plt.ylabel("|Kendall's tau|")
plt.xlim(left=0)
plt.axvline(np.log10(event_age), color='firebrick', lw=1.5, dashes=(2,1))
# plt.ylim(bottom=-0.004, top=0.016)
plt.colorbar().set_label("Minor allele Frequency")
plt.tight_layout()
plt.savefig(figPath+model_name+"_effect0Mut_absTau_vs_log10age_frequencyColor_legend2.png",
            dpi=300)
plt.close()

plt.scatter(np.log10(df["age"]),
            df["p_rank"],
            marker="o", c=df["freq"],
            alpha=0.01, s=20,
            vmin=0, vmax=0.5)
plt.xlabel("log10(Allele age)")
plt.ylabel("GEA p-values")
plt.xlim(left=0)
plt.axvline(np.log10(event_age), color='firebrick', lw=1.5, dashes=(2,1))
# plt.ylim(bottom=-0.004, top=0.016)
plt.colorbar().set_label("Minor allele Frequency")
plt.tight_layout()
plt.savefig(figPath+model_name+"_pRank_vs_log10age_frequencyColor.png",
            dpi=300)
plt.close()

