"""
Making summarizing plots for multiple SLiM runs, using the tables generated by
alleleAge_slimHistory.py
tianlin.duan42@gmail.com
2024.05.09
"""
############################# modules #########################################
import matplotlib
from scipy.spatial import distance_matrix
import PyQt6
import numpy as np
import random
from time import time
import glob #for loading files
from collections import Counter
import pandas as pd #dataframe
import os #mkdir
# matplotlib.use("qt5agg") # Not work
import matplotlib.pyplot as plt
from matplotlib import colormaps
import scipy.stats as stats
import sys # for sys.exit()
import matplotlib.patches as mpatches #manually make legends
import seaborn as sns

############################# options #############################
import argparse
parser = argparse.ArgumentParser()
# Path should end by "/"
parser.add_argument('-i', '--input',
                    help='Path to input tables',
                    type=str)
# #parser.add_argument('-n', '--name',
#                     help='Short model name',
#                     type=str)
# #parser.add_argument('-p', '--plot',
#                     help='1 for generating plots and 0 for not plotting',
#                     type=int, default=1)
args = parser.parse_args()

############################# program #########################################
# Values
# sigma_w = 0.4
# dist_mate = 0.12
num_runs = 200
inPath = args.input
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M2a_glacialHistoryOptimum0_clineMap_mu1.0e-10_sigmaM0.1_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07/tick110000/"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M3b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07/tick110000/"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M3b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07/tick110000/"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M2b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07/tick110000/"

simName = inPath.split("/")[-3]
#Short title: Hard coded. Check this before using!
if "sigmaD0.06_mateD0.15" in simName:
    migName = "HighMig"
elif "sigmaD0.03_mateD0.12" in simName:
    migName = "LowMig"
else:
    migName = ""
if "_clineMap_" in simName:
    mapName = "Cline"
elif "_patchyMap_" in simName:
    mapName = "Patchy"
else:
    mapName = ""
if "_sigmaM0.01_" in simName:
    mutName = "highPoly"
elif "_sigmaM0.1_" in simName:
    mutName = "lowPoly"
else:
    mutName = ""
demoName_ori = simName.split("_")[2]
# name_change = {"M2a":"M1a", "M2b":"M1b", "M3a":"M2a", "M3b":"M2b"}
name_change = {"M2a":"Single change", "M2b":"Single expansion", "M3a":"Recurrent changes", "M3b":"Recurrent expansions"}
demoName = name_change[demoName_ori]
shortName = ",".join([demoName, migName, mapName])

# figPath = ("/home/anadem/github/data/tskit_data/figure/multiRuns/" +
#            simName + "/" + str(num_runs) + "runs_" +
#            inPath.split("/")[-2]+"/")
figPath = ("/home/anadem/github/data/tskit_data/figure/multiRuns/test/" +
           simName + "/")
if not os.path.exists(figPath):
    os.makedirs(figPath)
# outPath = ("/home/anadem/github/data/tskit_data/output/mutiRuns/k80" +
#            simName + "/200runs_" + inPath.split("/")[-2]+"/")
outPath = ("/home/anadem/github/data/tskit_data/output/mutiRuns/test/")
if not os.path.exists(outPath):
    os.makedirs(outPath)

# Check this before use!
model_name = "_".join(inPath.split("/")[-3:-1] + [str(num_runs)+"runs"])
tick = int(inPath.split("/")[-2].split("tick")[-1])
event_age = tick - 100000
past_event_ages = [tick-i for i in list(range(0, 100000, 10000))]

# Shape of the table:
# dataTable[0]     mutation ID
# dataTable[1]     age,
# dataTable[2]     freq,
# dataTable[3]     mut_effect,
# dataTable[4]     delta_LF_mut,
# dataTable[5]     cor_GE[0]: Kandell's tau
# dataTable[6]     cor_GE[1]: p-value
# dataTable[7]     relative to the sum of positive delta_LF_mut (delta_LF_mut/sum of positive LF_mut )
# dataTable[8]     relative to sum of delta_LF_mut (delta_LF_mut/sum of LF_mut )
# dataTable[9]     temperary run ID 0,1,2...(number of files-1)
# dataTable[10]    rank of p-values
df = pd.DataFrame()
# Load results of multiple runs from file
fileList = glob.glob(inPath + "*.txt")
run = 0
for f in fileList:
    # df_focal = pd.read_csv(f, sep='\t', header=0)
    df_focal = pd.read_csv(f, sep="\t", header=0)
    # Add relative delta_LF_mut,temporary run ID, and rank of p-values
    lf_sum_positive = sum(df_focal.loc[df_focal["delta_LF_mut"]>0,"delta_LF_mut"])
    lf_sum_negative = sum(df_focal.loc[df_focal["delta_LF_mut"]<0, "delta_LF_mut"])
    lf_sum = sum(df_focal["delta_LF_mut"])
    df_focal["relative_positive_lf"] = (df_focal["delta_LF_mut"] /
                                        lf_sum_positive)
    df_focal["relative_negative_lf"] = (df_focal["delta_LF_mut"] /
                                        lf_sum_negative)
    df_focal["relative_lf"] = df_focal["delta_LF_mut"] / lf_sum
    df_focal["run_id"] = np.full(shape=(df_focal.shape[0], 1),
                                         fill_value=run)
    # df_focal["p_rank"] = df_focal["p"].argsort().argsort()
    df_focal["p_rank"] = df_focal["p"].rank(ascending=True, pct=True)
    df = pd.concat([df, df_focal], axis=0)
    run += 1
print(str(run) + " files have been loaded.")
# Columns: "id", "age", "freq", "mut_effect","delta_LF_mut",
#          "tau", "p", "relative_positive_lf", "relative_negative_lf", "relative_lf",
#          "run_id", "p_rank"



#### Make plots similar to FPR in M0 models
#FPR ~ Allele age (equal time intervals) in neutral alleles
maf_filter = 0.05
# df_plot = df[(df["mut_effect"] == 0) &
#                 (df["freq"] != 0) &
#                 (df["freq"] != 1)]
#Separate neutral alleles with MAF > 0.05
df_plot = df[(df["mut_effect"] == 0) &
                (df["freq"] >= maf_filter) &
                (df["freq"] <= (1-maf_filter))]

# False negative rate for NEUTRAL mutations among AGE categories: Equal intervals
num_cat_age = 22
# num_cat_age = 55
# p_threshold = 0.0001
p_threshold = 0.0000000001
max_age = tick
cat_width_age = max_age/num_cat_age
age_boundaries = np.append(np.arange(0, max_age, cat_width_age), max_age)
FPR_neutral_byAge_equalWidth = []
sample_size_age_equalWidth = []
p_median_byAge_equalWidth = []
p_sd_byAge_equalWidth = []
tau_absMedian_byAge_equalWidth = []
tau_absSd_byAge_equalWidth = []
for i in range(num_cat_age):
    p_category = df_plot["p"][(df_plot["age"] > age_boundaries[i]) &
                                 (df_plot["age"] <= age_boundaries[i+1])]
    tau_category = df_plot["tau"][(df_plot["age"] > age_boundaries[i]) &
                                 (df_plot["age"] <= age_boundaries[i+1])]
    sample_size_age_equalWidth.append(len(p_category))
    p_median_byAge_equalWidth.append(np.nanmedian(p_category))
    p_sd_byAge_equalWidth.append(np.nanstd(p_category))
    tau_absMedian_byAge_equalWidth.append(np.nanmedian(abs(tau_category)))
    tau_absSd_byAge_equalWidth.append(np.nanstd(abs(tau_category)))
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < p_threshold
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byAge_equalWidth.append(FP/mut_in_cat)


# Equal intervals
age_fig_size = (7,5) # 22 bins
# age_fig_size = (8,5) # 40 bins
# age_fig_size = (15,5) # 100 bins
# age_fig_size = (9,5) # 55 bins
label_font = 16
tick_font = 16
x = age_boundaries[0:-1] + cat_width_age/2
y = FPR_neutral_byAge_equalWidth
# Neutral alleles: FPR ～ Allele age, equal intervals
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(x,
         y,
         color="grey",
         marker = "o")
plt.xlabel("Allele age (thousand ticks)", fontsize=label_font)
plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=label_font)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i/1000)) for i in age_boundaries],
           rotation=90)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title("_".join([demoName, mutName, migName, mapName]), fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat_age)+"bins"+"_FPR_vs_age_neutralAllele_GEAp" + str(p_threshold) +
            "_maf" + str(maf_filter) +
            "_equalInterval.png",
            dpi=300)
plt.close()

#Save the FPR~age table for combined figures
outPath_fpr = outPath + "fpr/singleModel/"
if not os.path.exists(outPath_fpr):
    os.makedirs(outPath_fpr)
out_path_file = (outPath_fpr + model_name +
                 "_p" + str(p_threshold) +
                 "_maf"+str(maf_filter) +
                 "_cat" + str(num_cat_age)+ "_fpr.tab")
header = "\t".join(["age", "fpr", "tick_text"]) + "\n"
with open(out_path_file, "w") as fout:
    fout.write(header)
    for i in range(len(x)):
        outLine = "\t".join([str(x[i]), str(y[i]), str(age_boundaries[i])]) + "\t" +"\n"
        fout.write(outLine)
fout.close()
print("FPR table has been saved.")




# Neutral alleles: tau ～ Allele age, equal intervals
num_cat_age = 22
# num_cat_age = 55
max_age = tick
cat_width_age = max_age/num_cat_age
age_boundaries = np.append(np.arange(0, max_age, cat_width_age), max_age)
#List of lists of tau in age intervals
p_by_ageCat = []
log10p_by_ageCat = []
tau_by_ageCat = []
log10tau_by_ageCat = []
for i in range(num_cat_age):
    p_category = df_plot["p"][(df_plot["age"] > age_boundaries[i]) &
                                 (df_plot["age"] <= age_boundaries[i+1])]
    p_by_ageCat.append(p_category)
    log10p_by_ageCat.append([-np.log10(p) for p in p_category])
    tau_category = df_plot["tau"][(df_plot["age"] > age_boundaries[i]) &
                                 (df_plot["age"] <= age_boundaries[i+1])]
    tau_by_ageCat.append(tau_by_ageCat)
    log10tau_by_ageCat.append([-np.log10(tau) for tau in tau_category])

#Check sample size
[len(i) for i in log10p_by_ageCat]

#Boxplot: p, tau by age categories
age_fig_size = (7,5) # 22 bins
# age_fig_size = (10,5) # 55 bins
label_font = 16
tick_font = 16
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.boxplot(log10p_by_ageCat)
plt.xlabel("Allele age (thousand ticks)", fontsize=label_font)
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("-log10(p-value)",
           fontsize=label_font)
plt.xticks(ticks=list(range(num_cat_age+1)),
           labels=[str(int(i/1000)) for i in age_boundaries],
           rotation=90)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title("_".join([demoName, mutName, migName, mapName]))
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat_age)+"bins"+"_GEAp_vs_age_neutralAllele_box" +
            "_maf" + str(maf_filter) +
            "_equalInterval.png",
            dpi=300)
plt.close()


#### K80: Cumulative plots of LF_mut ####
expected_explained_proportion = 0.8
cumulative_lf_list = []
gea_goal = []
explained = []
for i in range(num_runs):
    focal_relative_lf_mut = df.loc[df["run_id"] == i, "relative_positive_lf"]
    relative_positive_lf_mut = focal_relative_lf_mut[focal_relative_lf_mut > 0]
    sorted_lfmut = np.array(list(reversed(sorted(relative_positive_lf_mut))))
    # Trim the tails with near-0 contributions to ensure all runs have the same
    # number of mutations
    #sorted_lfmut = sorted_lfmut[0:minimum_muts-1]
    # positiveTotal = sum(sorted_lfmut)
    focal_cumulative_lf = [0] + [sum(sorted_lfmut[0:k+1])
                                 for k in range(len(sorted_lfmut))]
    #print(focal_cumulative_lf)
    # How many alleles do we need to account for 80% of current local adaptation?
    focal_gea_goal = sum(np.array(focal_cumulative_lf) < expected_explained_proportion)
    #print(focal_gea_goal)
    focal_explained = focal_cumulative_lf[focal_gea_goal]
    cumulative_lf_list.append(focal_cumulative_lf)
    gea_goal.append(focal_gea_goal)
    explained.append(focal_explained)

# Convert the "list of lists" to a numpy array by adding np.nan values to the end
max_num_positive_mut = len(max(cumulative_lf_list, key=len))
cumulative_lf = np.full(shape=(run, max_num_positive_mut), fill_value=np.nan)
for i in range(run):
    n = len(cumulative_lf_list[i])
    cumulative_lf[i][0:n] = cumulative_lf_list[i]

# mean_cumulative_lf = np.mean(cumulative_lf, axis=0)
# median_cumulative_lf = np.median(cumulative_lf, axis=0)
# mean_trim_len = np.count_nonzero(~np.isnan(mean_cumulative_lf))
# median_trim_len = np.count_nonzero(~np.isnan(median_cumulative_lf))

# Calculate mean and meadian and ignore np.nan values
mean_cumulative_lf = np.nanmean(cumulative_lf, axis=0)
median_cumulative_lf = np.nanmedian(cumulative_lf, axis=0)
mean_gea_goal = int(np.mean(gea_goal))
mean_explained = mean_cumulative_lf[mean_gea_goal]
median_gea_goal = int(np.mean(gea_goal))
median_explained = median_cumulative_lf[median_gea_goal]

#Save K80 as a table
outPath_k80 = outPath + "k80/singleModel/"
if not os.path.exists(outPath_k80):
    os.makedirs(outPath_k80)
out_path_file = (outPath_k80 + model_name + "_k80.txt")
header = "_".join([demoName, mutName, migName, mapName]) + "\n"
with open(out_path_file, "w") as fout:
    fout.write(header)
    for i in gea_goal:
        outLine = str(i) + "\n"
        fout.write(outLine)
fout.close()
print("K80 table has been saved.")

# Plot cumulative_lf: Median with range
label_font = 16
tick_font = 14
plt.figure(figsize=(7,5.2))
for i in range(run):
    y = np.array(cumulative_lf_list[i])
    x = range(len(y))
    plt.plot(x, y,
             color="lightseagreen", alpha = 0.05)
plt.plot(range(len(median_cumulative_lf)), median_cumulative_lf,
             color="black")
plt.xlabel("Mutations sorted in descending order of $LF_{mut}$", fontsize=label_font)
plt.ylabel("Cumulative proportion of positive $LF$", fontsize=label_font)
plt.plot([median_gea_goal, median_gea_goal], [0, median_explained],
         color="firebrick", linestyle="dotted")
plt.plot([0, median_gea_goal], [median_explained, median_explained],
         color="firebrick", linestyle="dotted")
plt.annotate(str(median_gea_goal), xy=(median_gea_goal+1, median_explained),
             xytext=(median_gea_goal + 1 + len(median_cumulative_lf)/40, 0),
             color="firebrick", fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.savefig(figPath + model_name +
            "_medianLFcumulative_positive_100runs_medianAndRange.png",
            dpi=300)
plt.close()


#### LFmut vs. single variable ####
label_font = 16
tick_font = 14
# Sum of LF of the size class ~ |phenotypic effect size|, separating positive and negative parts
# relative to the total LF of each run
num_cat = 20 # Number of categories for phenotypic effect
abs_effect = abs(df["mut_effect"])
lf_sum = []
lf_sum_positive = []
lf_sum_negative = []
alpha_cats = np.append(np.arange(0, max(abs_effect), max(abs_effect)/num_cat),
                       max(abs_effect))
for i in range(num_cat):
    lf_category = df["relative_lf"][np.logical_and(abs_effect > alpha_cats[i],
                                              abs_effect <= alpha_cats[i+1])]
    lf_sum.append(sum(lf_category)/num_runs)
    lf_sum_positive.append(sum(lf_category[lf_category > 0])/num_runs)
    lf_sum_negative.append(sum(lf_category[lf_category < 0])/num_runs)

# barplot
plt.figure(figsize=(7,5.5))
lf_sum_positive = np.array(lf_sum_positive)
lf_sum_negative = np.array(lf_sum_negative)
x = alpha_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
if "high" in mutName:
    bar_width = 0.002 # High polygenicity
    x_up = 0.05
elif "low" in mutName:
    bar_width = 0.016 # Low polygenicity
    x_up = 0.40
fig, ax = plt.subplots()
if "high" in mutName:
    bar_width = 0.002 # High polygenicity
elif "low" in mutName:
    bar_width = 0.013 # Low polygenicity
ax.bar(x, y1, color="mediumaquamarine",
        label="Positive",
       width=bar_width)
ax.bar(x, y2, color="saddlebrown",
        label="Negative",
       width=bar_width)
ax.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.xlabel("|Phenotypic effect size|", fontsize=label_font)
plt.ylabel("Relative contribution to local adaptation \n" + r"( $\it{\Sigma LF_{mut}}$ )", fontsize=label_font)
# plt.ylabel(r"$\it{\Sigma LF_{mut}}$", fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.xlim(0, x_up)
plt.ylim(-0.08, 0.3)
ax.legend(loc="upper right",
           title_fontsize=16,
           fontsize=16)
ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
            "_LF_by_absEffectSize_bin_positveAndnegative_lfRelative2EachRun_barPlot.png",
            dpi=300)
plt.close()



# Sum of LF from the age class ~ Allele age
label_font = 16
tick_font = 14
num_cat = 100 # Number of categories for allele age
# lf_sum = []
lf_sum_positive = []
lf_sum_negative = []
# age = np.log10(df["age"])
age = df["age"]
age_cats = np.append(np.arange(0, tick, tick/num_cat),
                     tick)
for i in range(num_cat):
    lf_category = df["relative_lf"][np.logical_and(age > age_cats[i],
                                              age <= age_cats[i+1])]
    # lf_sum.append(sum(lf_category)/num_runs)
    lf_sum_positive.append(sum(lf_category[lf_category > 0])/num_runs)
    lf_sum_negative.append(sum(lf_category[lf_category < 0])/num_runs)

#total LF of the age class ~ allele age (positive and negative)
# bar plot
plt.figure(figsize=(7,5.5))
lf_sum_positive = np.array(lf_sum_positive)
lf_sum_negative = np.array(lf_sum_negative)
x = age_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
plt.bar(x, y1, color="mediumaquamarine",
       label="Positive",
       width=max(age)*0.9/num_cat)
plt.bar(x, y2, color="saddlebrown",
       label="Negative",
       width=max(age)*0.9/num_cat)
# plt.xlim(0, tick*1.05)
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.axvline(event_age, color='firebrick', lw=1, dashes=(2,1))
#For model M3a, M3b, mark the times of the start of each cycle of environmental changes
if "3" in demoName_ori:
    for cycle_time in past_event_ages:
        plt.axvline(cycle_time, color='lightgrey', lw=1, dashes=(2, 1))
# plt.xticks(ticks=np.arange(0, max(x), max(x)/10),
#            labels=['{:0.2e}'.format(i)
#                    for i in np.arange(0, max(x), max(x)/10)])
plt.xticks(ticks=range(0, tick+1, 10000),
           labels=[str(i) for i in range(0, tick+1, 10000)])
plt.tick_params(axis='x', rotation=45)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.xlabel("Allele age (generation)", fontsize=label_font)
plt.ylabel("Relative contribution to local adaptation \n" + r"( $\it{\Sigma LF_{mut}}$ )",
           fontsize=label_font)
plt.legend(loc="upper right",
           title_fontsize=16,
           fontsize=16)
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
            "_LF_by_age_bin_positveAndnegative_lfRelative2EachRun.png",
            dpi=300)
plt.close()

# #Test the shape of distribution
# #Log transformed pdf should be a straight line, with a slope of log10(lamda)
# plt.figure(1)
# plt.plot(age_cats[1:],np.log10(lf_sum_positive[0:]))
# plt.savefig(figPath+model_name+"_"+str(num_cat) + "log10_contribution_test.png",
#             dpi=300)
# plt.close()
#
# age_cdf = np.cumsum(lf_sum_positive)/max(np.cumsum(lf_sum_positive))
# exp_cdf = stats.expon.cdf(np.arange(0,1, 0.01), scale=0.23)
# plt.figure(1)
# plt.plot(age_cats[1:],age_cdf, "firebrick")
# plt.plot(age_cats[1:],exp_cdf, "grey")
# plt.savefig(figPath+model_name+"_"+str(num_cat) + "compare_cdf_test2.png",
#             dpi=300)
# plt.close()



# Contribution to local adaptation by frequency bins
num_cat = 25 # Number of categories for allele age
# lf_sum = []
lf_sum_positive = []
lf_sum_negative = []
freq = df["freq"]
freq_cats = np.append(np.arange(0, 1, 1.0/num_cat),
                     1)
for i in range(num_cat):
    lf_category = df["relative_lf"][np.logical_and(freq > freq_cats[i],
                                              freq <= freq_cats[i+1])]
    lf_sum.append(sum(lf_category)/num_runs)
    lf_sum_positive.append(sum(lf_category[lf_category > 0])/num_runs)
    lf_sum_negative.append(sum(lf_category[lf_category < 0])/num_runs)

# bar plot
plt.figure(figsize=(7,5.5))
lf_sum_positive = np.array(lf_sum_positive)
lf_sum_negative = np.array(lf_sum_negative)
x = freq_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
plt.bar(x, y1, color="mediumaquamarine",
       label="Positive",
       width=0.035)
plt.bar(x, y2, color="saddlebrown",
       label="Negative",
       width=0.035)
# plt.ylim(-0.1, 0.2) #temperary use
plt.ylim(-0.3, 0.4) # A value for all 8 combinations
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in 10**np.arange(0, max(x), 1)])
# plt.tick_params(axis='x', rotation=45)
plt.xlabel("Frequency", fontsize=label_font)
plt.ylabel("Relative contribution to local adaptation \n" + r"( $\it{\Sigma LF_{mut}}$ )",
           fontsize=label_font)
ax.legend(loc="upper right",
           title_fontsize=16,
           fontsize=16)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_cat) + "bins"+
            "_LF_by_freq_bin_positveAndnegative_lfRelative2EachRun.png",
            dpi=300)
plt.close()



#### Three-way relationship among allele frequency, effect size and contribution to LF

#### Scatter plot of allele frequency, phenotypic effect size and LF_mut
df_polymorphic = df[(df["freq"] != 1) & (df["freq"] != 0)]
max_lf = max(df_polymorphic["delta_LF_mut"])
min_lf = min(df_polymorphic["delta_LF_mut"])

# Use minor allele frequency for color
minor_freq = []
for f in df_polymorphic["freq"]:
    if f <= 0.5:
        minor_freq.append(f)
    else:
        minor_freq.append(1-f)
minor_freq = np.array(minor_freq)

# LF_mut ~ |phenotypic effect size|, colored by minor allele frequency
# cmap_maf = sns.color_palette("Spectral", as_cmap=True)
min_abs_effect = min(abs(df_polymorphic["mut_effect"]))
max_abs_effect = max(abs(df_polymorphic["mut_effect"]))

label_font = 16
tick_font = 14
plt.figure(figsize=(7,5))
#Scatter plot, took a long time and ~23 GB memory
plt.scatter(abs(df_polymorphic["mut_effect"]), df_polymorphic["delta_LF_mut"],
            marker="o", c=minor_freq,
            alpha=0.1, s=20
            #, cmap=cmap_maf
            )
# #small one for testing label sizes
# plt.scatter(abs(df_polymorphic["mut_effect"][1:10]), df_polymorphic["delta_LF_mut"][1:10],
#             marker="o", c=minor_freq[1:10],
#             alpha=0.1, s=20
#             ,# cmap=cmap_maf
#             )
plt.xlabel("|Phenotypic effect size|",
           fontsize=label_font)
plt.ylabel("$LF_{mut}$",
           fontsize=label_font)
plt.xlim(left=min_abs_effect,
         right=max_abs_effect)
# plt.ylim(bottom=-0.004, top=max_lf)
plt.ylim(bottom=min_lf, top=max_lf)
cb=plt.colorbar()
cb.set_label("Minor allele Frequency", fontsize=16)
cb.ax.tick_params(labelsize=14, size=3, width=2)
cb.solids.set(alpha=1)
# plt.show()
# plt.colorbar().set_label("Minor allele Frequency", fontsize=16)
# plt.colorbar().set_ticks([0, 0.1, 0.2, 0.3, 0.4, 0.5])
# plt.colorbar().set_ticklabels(["0", "0.1", "0.2", "0.3", "0.4", "0.5"], fontsize=tick_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name+"_effectSize_vs_LFmut_minorFrequencyColor_spectral.png",
            dpi=300)
plt.close()

del df_polymorphic



# #### Three-way relationship 1: 10 size categories, with labels               #KEEP
# # Sum of LF from the age class ~ Allele age Colored by |effect size|
# age = df["age"]
# size = abs(df["mut_effect"])
# num_age_cat = 100 # Number of categories for allele age
# num_size_cat = 10 #
# size_cats_step = 0.01
# size_last_tick = 0.1 # temporary
# # #Flexible categories:up to 10 but can be fewer
# # max_abs_size = max(size)
# # if size_last_tick > max_abs_size:
# #     num_size_cat = round(max(size) / size_cats_step)  # Number of categories for phenotypic effect size
# #     size_last_tick = size_cats_step*num_size_cat
# # lf_sum = []
# lf_sum_positive_size = np.full(shape=(10, 100), fill_value=np.nan)
# lf_sum_negative_size = np.full(shape=(10, 100), fill_value=np.nan)
# age_cats = np.append(np.arange(0, max(age), max(age)/num_age_cat),
#                      max(age))
# size_cats = np.r_[np.arange(0, size_last_tick, size_cats_step), max(size)]
# for i in range(num_age_cat):
#     for j in range(num_size_cat):
#         focal_range = np.logical_and(np.logical_and(age > age_cats[i],
#                                                     age <= age_cats[i+1]),
#                                      np.logical_and(abs(size) > size_cats[j],
#                                                     abs(size) <= size_cats[j+1]))
#         lf_category = df["relative_lf"][focal_range]
#         lf_sum_positive_size[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
#         lf_sum_negative_size[j][i] = (sum(lf_category[lf_category < 0])/num_runs)
#
# y1 = lf_sum_positive_size
# y2 = lf_sum_negative_size
# # bar plot
# plt.figure(1)
# x = age_cats[1:]
# # colors = ["#FDE257FF", "#95D840FF", "#29AF7FFF","#287D8EFF","#440154FF"]
# # viridis 10 categories
# colors = ["#FDE725FF", "#AADC32FF", "#5DC863FF", "#27AD81FF", "#1F9A8AFF",
#           "#287C8EFF", "#365D8DFF","#443A83FF", "#481F70FF", "#440154FF"]
# patches = []
# for i in range(num_size_cat-1):
#     patches.append(mpatches.Patch(color=colors[i], label= str(i*size_cats_step) +
#                                                           "-" + str((i+1)*size_cats_step)))
# #The last patch:
# patches.append(mpatches.Patch(color=colors[num_size_cat-1], label="> " + str(round(size_last_tick-size_cats_step,2))))
# # Initialize the vertical-offset for the stacked bar chart.
# bar_width = tick/110
# y_offset = np.zeros(num_age_cat)
# for row in range(num_size_cat):
#     plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
#     y_offset = y_offset + y1[row]
# y_offset = np.zeros(num_age_cat)
# for row in range(num_size_cat):
#     plt.bar(x, y2[row], bar_width, bottom=y_offset, color=colors[row])
#     y_offset = y_offset + y2[row]
# plt.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.axvline(event_age, color='firebrick', lw=1, dashes=(2,1), zorder=0)
# # plt.xticks(ticks=np.arange(0, max(x), 1),
# #            labels=['{:0.2e}'.format(i)
# #                    for i in 10**np.arange(0, max(x), 1)])
# plt.tick_params(axis='x', rotation=45)
# plt.xlabel("Allele age (generation)")
# plt.ylabel(r"Relative contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ )")
# plt.ylim(np.min(np.nansum(y2, axis = 0))*1.2, np.max(np.nansum(y1, axis=0))*1.2)
# plt.legend(handles=patches,
#            title="|Mutation phenotypic effect size|",
#            loc="upper center")
# # ax.legend(loc="upper right")
# # ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# # ax.margins(x=0)
# plt.title(shortName)
# plt.tight_layout()
# plt.savefig(figPath+model_name+"_"+str(num_age_cat) + "bins"+
#             "_LF_by_age_bin_positve_lfRelative2EachRun_sizeColor.png",
#             dpi=300)
# plt.close()

#Three-way relationship 1: no log:20 categories, no labels
# Sum of LF from the age class ~ Allele age Colored by |effect size|
age = df["age"]
size = abs(df["mut_effect"])
num_age_cat = 100 # Number of categories for allele age
num_size_cat = 20 #
size_cats_step = 0.01
size_last_tick = 0.2 # temporary
# #Flexible categories:up to 10 but can be fewer
# max_abs_size = max(size)
# if size_last_tick > max_abs_size:
#     num_size_cat = round(max(size) / size_cats_step)  # Number of categories for phenotypic effect size
#     size_last_tick = size_cats_step*num_size_cat
# lf_sum = []
lf_sum_positive_size = np.full(shape=(20, 100), fill_value=np.nan)
lf_sum_negative_size = np.full(shape=(20, 100), fill_value=np.nan)
age_cats = np.append(np.arange(0, max(age), max(age)/num_age_cat),
                     max(age))
size_cats = np.r_[np.arange(0, size_last_tick, size_cats_step), max(size)]
for i in range(num_age_cat):
    for j in range(num_size_cat):
        focal_range = np.logical_and(np.logical_and(age > age_cats[i],
                                                    age <= age_cats[i+1]),
                                     np.logical_and(abs(size) > size_cats[j],
                                                    abs(size) <= size_cats[j+1]))
        lf_category = df["relative_lf"][focal_range]
        lf_sum_positive_size[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
        lf_sum_negative_size[j][i] = (sum(lf_category[lf_category < 0])/num_runs)

y1 = lf_sum_positive_size
y2 = lf_sum_negative_size
label_font = 16
tick_font = 14
# # viridis 10 categories
# colors = ["#FDE725FF", "#AADC32FF", "#5DC863FF", "#27AD81FF", "#1F9A8AFF",
#           "#287C8EFF", "#365D8DFF","#443A83FF", "#481F70FF", "#440154FF"]
# # viridis 20 categories
# colors = ["#FDE725FF", "#DCE319FF", "#B8DE29FF", "#95D840FF", "#73D055FF",
#            "#55C667FF", "#3CBB75FF","#29AF7FFF", "#20A387FF", "#1F968BFF",
#           "#238A8DFF", "#287D8EFF","#2D708EFF", "#33638DFF", "#39568CFF",
#           "#404788FF", "#453781FF","#482677FF", "#481567FF", "#440154FF"]
#Modified viridis
colors = ["#FDE725FF", "#cce010FF", "#a2d115FF", "#68cf1fFF", "#34c421FF",
           "#2bba44FF", "#3CBB75FF","#29AF7FFF", "#20A387FF", "#1F968BFF",
          "#238A8DFF", "#287D8EFF","#2D708EFF", "#33638DFF", "#39568CFF",
          "#404788FF", "#453781FF","#482677FF", "#481567FF", "#440154FF"]
# bar plot
plt.figure(figsize=(6,4.5))
x = age_cats[1:]
patches = []
for i in range(num_size_cat-1):
    patches.append(mpatches.Patch(color=colors[i], label= str(i*size_cats_step) +
                                                          "-" + str((i+1)*size_cats_step)))
#The last patch:
patches.append(mpatches.Patch(color=colors[num_size_cat-1], label="> " + str(round(size_last_tick-size_cats_step,2))))
# Initialize the vertical-offset for the stacked bar chart.
bar_width = tick/110
y_offset = np.zeros(num_age_cat)
for row in range(num_size_cat):
    plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + y1[row]
y_offset = np.zeros(num_age_cat)
for row in range(num_size_cat):
    plt.bar(x, y2[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + y2[row]
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.axvline(event_age, color='firebrick', lw=1,
            dashes=(2,1), zorder=0)
#For model M3a, M3b, mark the times of the start of each cycle of environmental changes
if "3" in demoName_ori:
    for cycle_time in past_event_ages:
        plt.axvline(cycle_time, color='lightgrey',
                    lw=1, dashes=(2, 1), zorder=0)
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in 10**np.arange(0, max(x), 1)])
plt.tick_params(axis='x', rotation=10)
plt.tick_params(axis='both', labelsize=tick_font, size=3, width=2)
# plt.xlabel("Allele age (ticks)", fontsize=label_font)
# plt.ylabel(r"Relative contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ )", fontsize=label_font)
# plt.ylabel(r" $\it{\Sigma LF_{mut}}$ ", fontsize=label_font)
plt.ylim(np.min(np.nansum(y2, axis = 0))*1.2, np.max(np.nansum(y1, axis=0))*1.2)
# plt.legend(handles=patches,
#            title="|Mutation phenotypic effect size|",
#            loc="center left", bbox_to_anchor=(1, 0.5),
#            fontsize="x-large")
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_age_cat) + "bins"+
            "_LF_by_age_bin_positve_lfRelative2EachRun_sizeColor.png",
            dpi=300)
plt.close()

#Standalone colorbar for 20-category effect size
plt.figure(figsize=(3,7.5)) #ncol=1
# plt.figure(figsize=(4.2,4)) #ncol=2
x = age_cats[1:]
patches = []
for i in range(num_size_cat-1):
    patches.append(mpatches.Patch(color=colors[i], label= str(i*size_cats_step) +
                                                          "-" + str((i+1)*size_cats_step)))
patches.append(mpatches.Patch(color=colors[num_size_cat-1], label="> " + str(round(size_last_tick-size_cats_step,2))))
# im=plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
# # im.set_visible(False)
plt.legend(handles=patches,
           title="|Phenotypic effect size|",
           loc="center",
           title_fontsize=16,
           fontsize=16,
           ncol=1)
plt.tight_layout()
plt.axis('off')
plt.savefig(figPath + str(num_size_cat) + "bins"+
            "_sizeColor_colorBar1_2.png",
            dpi=300)
plt.close()



#Three-way relationship 2: (no log)
# Sum of LF from the age class ~ Allele age, Colored by frequency
num_age_cat = 100 # Number of categories for allele age
num_freq_cat = 10 # Number of categories for allele frequency
freq_cats_step = 0.1
freq_last_tick = 1.1 # not inclueded
# lf_sum = []
lf_sum_positive_freq = np.full(shape=(10, 100), fill_value=np.nan)
lf_sum_negative_freq = np.full(shape=(10, 100), fill_value=np.nan)
age = df["age"]
freq = df["freq"]

age_cats = np.append(np.arange(0, max(age), max(age)/num_age_cat),
                     max(age))
freq_cats = np.arange(0, freq_last_tick, freq_cats_step)
for i in range(num_age_cat):
    for j in range(num_freq_cat):
        focal_range = np.logical_and(np.logical_and(age > age_cats[i],
                                                    age <= age_cats[i + 1]),
                                     np.logical_and(freq > freq_cats[j],
                                                    freq <= freq_cats[j + 1]))
        lf_category = df["relative_lf"][focal_range]
        lf_sum_positive_freq[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
        lf_sum_negative_freq[j][i] = (sum(lf_category[lf_category < 0])/num_runs)

y1 = lf_sum_positive_freq
y2 = lf_sum_negative_freq
label_font = 16
tick_font = 14
# colors = ["#f2e5f9FF", "#dbcee9FF", "#b9a1d3FF", "#9B7DC5FF", "#7757adFF",
#           "#623f9cFF", "#51308cFF", "#3c1e7aFF", "#2c0f70FF", "#200462FF"]
colors = ["#d2ebf3FF", "#9dcde3FF", "#6899CEFF", "#4074cbFF", "#1839aaFF",
          "#1624a1FF", "#523cb7FF", "#8f69caFF", "#c2a0dfFF", "#e5d0f0FF"]

# bar plot
plt.figure(1)
x = age_cats[1:]
patches = []
for i in range(num_freq_cat):
    patches.append(mpatches.Patch(color=colors[i], label= str(round(i*freq_cats_step, 2)) +
                                                          "-" + str(round((i+1)*freq_cats_step, 2))))
# Initialize the vertical-offset for the stacked bar chart.
bar_width = tick/110
y_offset = np.zeros(num_age_cat)
for row in range(num_freq_cat):
    plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + y1[row]
y_offset = np.zeros(num_age_cat)
for row in range(num_freq_cat):
    plt.bar(x, y2[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + y2[row]
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
plt.axvline(event_age, color='firebrick',
            lw=1, dashes=(2,1),zorder=0)
#For model M3a, M3b, mark the times of the start of each cycle of environmental changes
if "3" in demoName_ori:
    for cycle_time in past_event_ages:
        plt.axvline(cycle_time, color='lightgrey',
                    lw=1, dashes=(2, 1), zorder=0)
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in 10**np.arange(0, max(x), 1)])
plt.tick_params(axis='x', rotation=10)
plt.tick_params(axis='both', labelsize=tick_font, size=3, width=2)
plt.xlabel("Allele age (ticks)",
           fontsize=label_font)
# plt.ylabel(r"Relative contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ )", fontsize=label_font)
plt.ylabel(r"$\it{\Sigma LF_{mut}}$",
           fontsize=label_font)
plt.ylim(np.min(np.sum(y2, axis = 0))*1.2, np.max(np.sum(y1, axis=0))*1.2)
plt.legend(handles=patches,
           title="Allele frequency",
           loc="upper center",
           ncols=2)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+model_name+"_"+str(num_age_cat) + "bins"+
            "_LF_by_age_bin_positve_lfRelative2EachRun_freqColor.png",
            dpi=300)
plt.close()

#Standalone Colorbar for frequency
plt.figure(figsize=(2.2,4)) #ncol=1
# plt.figure(figsize=(3.8,2.5)) #ncol=2
x = age_cats[1:]
patches = []
for i in range(num_freq_cat):
    patches.append(mpatches.Patch(color=colors[i], label= str(round(i*freq_cats_step, 2)) +
                                                          "-" + str(round((i+1)*freq_cats_step, 2))))
# im=plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
# # im.set_visible(False)
plt.legend(handles=patches,
           title="Allele frequency",
           loc="center",
           title_fontsize=16,
           fontsize=16,
           ncol=1)
plt.tight_layout()
plt.axis('off')
plt.savefig(figPath+model_name+"_"+str(num_size_cat) + "bins"+
            "_freqColor_colorBar1.png",
            dpi=300)
plt.close()



#Three-way relationship 3: no log
# Sum of LF from the size class ~ Effect size, Colored by frequency
abs_size = abs(df["mut_effect"])
num_size_cat = 20 # Number of categories for phenotypic effect
num_freq_cat = 10 # Number of categories for allele frequency
lf_sum_positive = np.full(shape=(10, 20), fill_value=np.nan)
lf_sum_negative = np.full(shape=(10, 20), fill_value=np.nan)
size_cats = np.append(np.arange(0, max(abs_size), max(abs_size)/num_size_cat),
                       max(abs_size))
freq_cats = np.arange(0,1.1, 0.1) # Hard coded
for i in range(num_size_cat):
    for j in range(num_freq_cat):
        focal_range = np.logical_and(np.logical_and(abs_size > size_cats[i],
                                                    abs_size <= size_cats[i + 1]),
                                     np.logical_and(freq > freq_cats[j],
                                                    freq <= freq_cats[j + 1]))
        # lf_category = df["relative_lf"][focal_range]
        lf_category = df["relative_positive_lf"][focal_range]
        lf_sum_positive[j][i] = (sum(lf_category[lf_category > 0])/num_runs)
        lf_sum_negative[j][i] = (sum(lf_category[lf_category < 0])/num_runs)

# bar plot
x = size_cats[1:]
y1 = lf_sum_positive
y2 = lf_sum_negative
# colors = ["#f2e5f9FF", "#dbcee9FF", "#b9a1d3FF", "#9B7DC5FF", "#7757adFF",
#           "#623f9cFF", "#51308cFF", "#3c1e7aFF", "#2c0f70FF", "#200462FF"]
colors = ["#d2ebf3FF", "#9dcde3FF", "#6899CEFF", "#4074cbFF", "#1839aaFF",
          "#1624a1FF", "#523cb7FF", "#8f69caFF", "#c2a0dfFF", "#e5d0f0FF"]
label_font = 16
tick_font = 14

plt.figure(1)
patches = []
for i in range(num_freq_cat):
    patches.append(mpatches.Patch(color=colors[i], label= str(round(i*freq_cats_step, 2)) +
                                                          "-" + str(round((i+1)*freq_cats_step, 2))))
# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.zeros(num_size_cat)
if "high" in mutName:
    bar_width = 0.002 # High polygenicity
    x_up = 0.05
elif "low" in mutName:
    bar_width = 0.016 # Low polygenicity
    x_up = 0.40
for row in range(num_freq_cat):
    plt.bar(x, y1[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + lf_sum_positive[row]
plt.axhline(0, color='grey', lw=1, dashes=(1,1))
# plt.axvline(np.log10(event_age), color='firebrick', lw=1, dashes=(2,1))
# plt.xticks(ticks=np.arange(0, max(x), 1),
#            labels=['{:0.2e}'.format(i)
#                    for i in np.arange(0, max(x), 0.005)])
# plt.tick_params(axis='x', rotation=45)
plt.tick_params(axis='both', labelsize=tick_font, size=3, width=2)
plt.xlabel("|Phenotypic effect size|", fontsize=label_font)
# plt.ylabel(r"Relative contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ )",
# fontsize=label_font)
plt.ylabel(r"$\it{\Sigma LF_{mut}}$", fontsize=label_font)
plt.ylim(0, 0.8)
plt.legend(handles=patches,
           title="Allele frequency",
           loc="upper right")
plt.xlim(0, x_up) # High polygenicity
plt.ylim(0, 0.3)
# ax.legend(loc="upper right")
# ax.yaxis.set_major_formatter(lambda x, pos: f'{abs(x):g}')
# ax.margins(x=0)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
# plt.savefig(figPath+model_name+"_"+str(num_size_cat) + "bins"+
#             "_LF_by_size_bin_positve_lfRelative2EachRun_freqColor.png",
#             dpi=300)
plt.savefig(figPath+model_name+"_"+str(num_size_cat) + "bins"+
            "_LF_by_size_bin_positve_lfRelative2PositiveLFEachRun_freqColor.png",
            dpi=300)
plt.close()
