"""
Making summarizing plots for multiple SLiM runs, using the tables generated by
alleleAge_slimHistory_fpr.py
tianlin.duan42@gmail.com
2024.07.23
"""
############################# modules #########################################
import matplotlib
import msprime
import pandas
import tskit
import pyslim
import matplotlib
import matplotlib.pyplot as plt
import scipy.stats as stats
from scipy.spatial import distance_matrix
import numpy as np
import random
from time import time
import sys # for sys.exit()
import allel # for allel.weir_cockerham_fst()
import glob #for loading files
from collections import Counter
import pandas #dataframe
import os #mkdir
# matplotlib.use("qt5agg") # Not work
import matplotlib.pyplot as plt
import scipy.stats as stats
import sys # for sys.exit()
import allel # for allel.weir_cockerham_fst()
import matplotlib.patches as mpatches # manually make legends
import seaborn as sns

############################# options #############################
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-i', '--input',
                    help='Path the the input tables',
                    type=str)
# parser.add_argument('-n', '--name',
#                     help='Short model name',
#                     type=str)
# parser.add_argument('-p', '--plot',
#                     help='1 for generating plots and 0 for not plotting',
#                     type=int, default=1)
args = parser.parse_args()

############################# program #########################################
# Values
# sigma_w = 0.4
# dist_mate = 0.12
num_runs = 20
# inPath = args.input
# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
# inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07/tick110000/"
inPath = "/home/tianlin/Documents/github/data/tskit_data/output/table/realistic_fpr_comparisons/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K5000_r1.0e-07/tick110000/"
short_model_name = inPath.split("/")[-3]

figPath = ("/home/tianlin/Documents/github/data/tskit_data/figure/20240722/multiple_runs_fpr/" +
           short_model_name + "/" + str(num_runs) + "runs_" +
           inPath.split("/")[-2]+"/")
# outPath = ("/home/tianlin/Documents/github/data/tskit_data/output/multiple_runs/" +
#            short_model_name + "/100runs_" + inPath.split("/")[-2]+"/")
# if not os.path.exists(outPath):
#     os.makedirs(outPath)
if not os.path.exists(figPath):
    os.makedirs(figPath)

# Check this before use!
model_name = "_".join(inPath.split("/")[-3:-1] + [str(num_runs)+"runs_"])
tick = int(inPath.split("/")[-2].split("tick")[-1])
event_age = tick - 100000

# Shape of the table:
# dataTable[0]     mutation ID
# dataTable[1]     age,
# dataTable[2]     freq,
# dataTable[3]     mut_effect,
# dataTable[4]     mean LF (single value for the whole population)
# dataTable[5]     cor_GE[0]: Kandell's tau
# dataTable[6]     cor_GE[1]: p-value
# dataTable[7]     temperary run ID 0,1,2...(number of files-1)
# dataTable[8]    rank of p-values
dataTable = np.empty((9, 0))
# Load results of multiple runs from file
fileList = glob.glob(inPath + "*.txt")
run = 0
lf_sums = []
for f in fileList:
    focalTable = np.loadtxt(f)
    # print(np.shape(focalTable))
    # Add relative positive delta_LF_mut (delta_LF_mut/sum of positive LF_mut)
    relative_positive_lf_mut = focalTable[4]/sum(focalTable[4][focalTable[4]>0])
    lf_sum = sum(focalTable[4])
    lf_sums.append(lf_sum)
    relative_lf_mut = focalTable[4] / sum(focalTable[4])
    p_rank = focalTable[6].argsort().argsort()
    # print(len(focalTable[0]))
    # Add temporary run ID, and rank of p-values
    focalTable = np.concatenate((focalTable,
                                 np.full(shape=(1, len(focalTable[0])),
                                         fill_value=run),
                                 [p_rank]),
                                axis=0)
    dataTable = np.concatenate((dataTable, focalTable), axis=1)
    run += 1

# Change to pandas dadaframe
dataTable_t = dataTable.transpose()
df = pandas.DataFrame(data=dataTable_t,
                      columns=["id", "age", "freq",
                               "effect_size","mean_LF","tau",
                               "p",
                               "run_id", "p_rank"])

# True positive rate, False negative rate, False discovery rate
# True adaptive allele: account for more than LF_min percent of positve LF_mut
# GEA significant: BH-adjusted p-value < 0.05
LF_min = 0.01
num_cat = 20
cat_width = int(100/num_cat) if 100 % num_cat == 0 else 100/num_cat
age_percentile = np.percentile(dataTable[1],
                               np.append(np.arange(0, 100, cat_width),
                                         100))
event_percentile = stats.percentileofscore(dataTable[1], event_age)
FPR = []
for i in range(num_cat):
    focal_age = np.logical_and(dataTable[1] > age_percentile[i],
                               dataTable[1] <= age_percentile[i+1])
    dataTable_category = dataTable[:, focal_age]
    # num_allele = len(p_BH_category)
    # proportion_sig.append(sum(p_BH_category < 0.05)/num_allele)
    expP = dataTable_category[7] > LF_min
    obsP = dataTable_category[6] < 0.05
    TP = sum(expP & obsP)
    FP = sum(~expP & obsP)
    FN = sum(expP & ~obsP)
    TN = sum(~expP & ~obsP)
    FPR.append(FP/(TN+FP))

#### Separate neutral alleles
# mutation ID, allele age, allele frequency, mutation effect, LF_mut,
# GEA Kendall's tau and corresponding p-value
# Separate neutral alleles and remove lost or fixed alleles
df_neutral = df[(df["effect_size"] == 0) &
                (df["freq"] != 0) &
                (df["freq"] != 1)]
num_neutral_muts = df_neutral.shape[0]

# Check here before use
num_cat = 10
bin_width = 100/num_cat

# False negative rate for NEUTRAL mutations among AGE categories
# Equal numbers
cat_width = int(100/num_cat) if 100 % num_cat == 0 else 100/num_cat
age_percentile = np.percentile(df_neutral["age"],
                               np.append(np.arange(0, 100, cat_width),
                                         100))
FPR_neutral_byAge = []
for i in range(num_cat):
    p_category = df_neutral["p"][(df_neutral["age"] > age_percentile[i]) &
                                 (df_neutral["age"] <= age_percentile[i+1])]
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < 0.05
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byAge.append(FP/mut_in_cat)

# False negative rate for NEUTRAL mutations among AGE categories
# Equal width
num_cat_age = 20
max_age = tick
cat_width_age = max_age/num_cat_age
age_boundaries = np.append(np.arange(0, max_age, cat_width_age), max_age)
FPR_neutral_byAge_equalWidth = []
sample_size_age = []
for i in range(num_cat_age):
    p_category = df_neutral["p"][(df_neutral["age"] > age_boundaries[i]) &
                                 (df_neutral["age"] <= age_boundaries[i+1])]
    sample_size_age.append(len(p_category))
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < 0.05
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byAge_equalWidth.append(FP/mut_in_cat)

# False negative rate for NEUTRAL mutations among FREQUENCY categories
# Equal numbers
# Neutral mutations have no phenotypic effect and therefore no positve
cat_width = int(100/num_cat) if 100 % num_cat == 0 else 100/num_cat
freq_percentile = np.percentile(df_neutral["freq"],
                               np.append(np.arange(0, 100, cat_width),100))
FPR_neutral_byFreq = []
for i in range(num_cat):
    if freq_percentile[i] != freq_percentile[i+1]:
        p_category = df_neutral["p"][(df_neutral["freq"] > freq_percentile[i]) &
                                     (df_neutral["freq"] <= freq_percentile[i+1])]
    else:
        # The frequency of singletons exceed bin width: Use the all singletons
        p_category = df_neutral["p"][df_neutral["age"] == age_percentile[i]]
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < 0.05
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byFreq.append(FP/mut_in_cat)

# False negative rate for NEUTRAL mutations among FREQ categories
# Equal intervals
num_cat_freq = 20
cat_width_freq = 1.0/num_cat_freq
freq_boundaries = np.append(np.arange(0, 1.0, cat_width_freq), 1.0)
FPR_neutral_byFreq_equalWidth = []
sample_size_freq = []
for i in range(num_cat_freq):
    p_category = df_neutral["p"][(df_neutral["freq"] > freq_boundaries[i]) &
                                 (df_neutral["freq"] <= freq_boundaries[i+1])]
    print(len(p_category))
    sample_size_freq.append(len(p_category))
    # Neutral mutations have no phenotypic effect and therefore no positive
    mut_in_cat = len(p_category)
    obsP_neutral = p_category < 0.05
    # All positives are false positives
    FP = sum(obsP_neutral)
    FPR_neutral_byFreq_equalWidth.append(FP/mut_in_cat)

#### Plots ####
# Neutral alleles: FPR ～ Allele age, equal number alleles per bin
plt.plot(np.arange(100/num_cat, 101, 100/num_cat) + 0.5*bin_width,
         FPR_neutral_byAge,
         color="grey",
         marker = "o")
plt.xlabel("\n\nAllele age percentile bins")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
for i in range(num_cat + 1):
    label = str(int(age_percentile[i]))
    x = np.arange(100/num_cat, 101+bin_width, 100/num_cat)[i]
    y = -0.06 * max(FPR_neutral_byAge)
    # if i != 0:
    #     y = (FPR_neutral_byFreq[i] + FPR_neutral_byFreq[i-1])/2
    # else:
    #     y = FPR_neutral_byFreq[i] / 2
    plt.annotate(label,
                 (x,y),
                 textcoords="offset points",
                 xytext=(-0.5*bin_width, -0.5*bin_width),
                 annotation_clip=False,
                 color="grey")
    plt.xticks([], minor=False)
plt.xticks(ticks=np.arange(100/num_cat, 101+bin_width, 100/num_cat),
           labels=[str(int(i*cat_width)) for i in range(num_cat+1)])
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins"+"_FPR_GEAp0.05_vs_age_neutralAllele.png",
            dpi=300)
plt.close()

# Neutral alleles: FPR ～ Frequency, equal number alleles per bin
plt_pos = np.arange(100/num_cat, 101, 100/num_cat) - 5
plt.plot(plt_pos,
         FPR_neutral_byFreq,
         color="grey",
         marker = "o")
plt.xlabel("\n\n\nAllele frequency percentile bins")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
for i in range(num_cat + 1):
    label = "{:.5f}".format(freq_percentile[i])
    print(label)
    x = np.arange(0, 101+bin_width, 100/num_cat)[i]
    y = -0.30 * max(FPR_neutral_byFreq)
    plt.annotate(label,
                 (x,y),
                 textcoords="offset points",
                 xytext=(-1*bin_width, 0.5*bin_width),
                 annotation_clip=False,
                 color="grey",
                 rotation = 45)
    plt.xticks([], minor=False)
plt.xticks(ticks=np.arange(0, 101, 100/num_cat),
           labels=[str(int(i*cat_width)) for i in range(num_cat+1)])
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat)+"bins"+"_FPR_GEAp0.05_vs_freq_neutralAllele.png",
            dpi=300)
plt.close()

# Neutral alleles: FPR ～ Allele age, equal intervals
plt.plot(age_boundaries[0:-1] + cat_width_age/2,
         FPR_neutral_byAge_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele age")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i)) for i in age_boundaries],
           rotation=45)
plt.tight_layout()
plt.savefig(figPath+model_name +
            str(num_cat_age)+"bins"+"_FPR_GEAp0.05_vs_age_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Neutral alleles: FPR ～ Allele frequency, equal intervals
plt.plot(freq_boundaries[0:-1] + cat_width_freq/2,
         FPR_neutral_byFreq_equalWidth,
         color="grey",
         marker = "o")
plt.xlabel("Allele frequency")
# plt.ylabel("Proportion of alleles with BH-adjusted p-value < 0.05")
plt.ylabel("False positive rate of neutral alleles (FP/(FP+TN))")
plt.xticks(ticks=freq_boundaries,
           labels=[str(round(i,2)) for i in freq_boundaries],
           rotation=45)
plt.tight_layout()
plt.savefig(figPath + model_name +
            str(num_cat_freq)+"bins"+"_FPR_GEAp0.05_vs_freq_neutralAllele_equalInterval.png",
            dpi=300)
plt.close()

# Histogram of allele age of neutral alleles
plt.hist(df_neutral["age"], bins=100,
         color="grey")
plt.xlabel("Allele age")
plt.ylabel("Count")
plt.savefig(figPath+model_name+"_age_hist_neutral.png",
            dpi=300)
plt.close()

# Histogram of allele freq of neutral alleles
plt.hist(df_neutral["freq"], bins=100,
         color="grey")
plt.xlabel("Allele frequency")
plt.ylabel("Count")
plt.savefig(figPath+model_name+"_freq_hist_neutral.png",
            dpi=300)
plt.close()

# Histogram of allele freq of neutral alleles
plt.hist(df["freq"], bins=100,
         color="grey")
plt.xlabel("Allele frequency")
plt.ylabel("Count")
plt.savefig(figPath+model_name+"_freq_hist.png",
            dpi=300)
plt.close()

