"""
Make plots with results of multiple SLim models,
using .tab files generated by alleleAge_multiRuns.py
tianlin.duan42@gmail.com
2025.08.05
"""
############################# modules #########################################
import matplotlib
import matplotlib.pyplot as plt
import os #mkdir
import pandas as pd #dataframe

############################# program #########################################
num_runs = 200
figPath = "/home/anadem/github/data/tskit_data/figure/multiModels/v1.0/"
if not os.path.exists(figPath):
    os.makedirs(figPath)

#Check the following values before using
num_cat_age = 22 #number of bins
cat_width_age = 5000.0
p_threshold = 0.0000000001
maf_filter = 0.05
age_fig_size = (9,6) # 22 bins
alpha_line=0.8
label_font = 16
tick_font = 16
legend_font = 16

#Contrast the effect of environmental map
#Constant pop, cline
f1 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df1 = pd.read_csv(f1, sep="\t", header=0, index_col=False)
#Constant pop, patchy
f2 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2a_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df2 = pd.read_csv(f2, sep="\t", header=0, index_col=False)

# Single expansion, cline
f3 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df3 = pd.read_csv(f3, sep="\t", header=0, index_col=False)
# Single expansion, patchy
f4 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df4 = pd.read_csv(f4, sep="\t", header=0, index_col=False)

# Multiple expansions, cline
f5 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M3b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df5 = pd.read_csv(f5, sep="\t", header=0, index_col=False)
# Multiple expansions, patchy
f6 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M3b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df6 = pd.read_csv(f6, sep="\t", header=0, index_col=False)

age_boundaries = list(df1["tick_text"]) + [110000.0]

# Neutral alleles: FPR ～ Allele age, equal intervals
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(df1["age"],
         df1["fpr"],
         color="mediumaquamarine",
         marker = "s",
         alpha=alpha_line,
         label = " ")
plt.plot(df3["age"],
         df3["fpr"],
         color="mediumaquamarine",
         marker = "<",
         alpha=alpha_line,
         label = " ")
plt.plot(df5["age"],
         df5["fpr"],
         color="teal",
         marker = "D",
         alpha=alpha_line,
         label = " ")
plt.plot(df2["age"],
         df2["fpr"],
         color="mediumaquamarine",
         marker = "s",
         fillstyle="none",
         # linestyle='dotted',
         alpha=alpha_line,
         label = "Constant pop.")
plt.plot(df4["age"],
         df4["fpr"],
         color="mediumaquamarine",
         marker = "<",
         fillstyle="none",
         # linestyle='dotted',
         alpha=alpha_line,
         label = "Single pop. expansion")
plt.plot(df6["age"],
         df6["fpr"],
         color="teal",
         marker = "D",
         fillstyle="none",
         # linestyle='dotted',
         alpha=alpha_line,
         label = "Recurrent pop. expansions")
plt.xlabel("Allele age (thousand ticks)", fontsize=label_font)
plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=label_font)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i/1000)) for i in age_boundaries],
           rotation=90)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.legend(loc="center",
           title="  Env. map \nCline   Patchy",
           title_fontsize=legend_font,
           fontsize=legend_font,
           ncol=2,
           columnspacing=0.5)._legend_box.align = "left"
# plt.title("", fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+"fpr_comparison1" +
            str(num_cat_age)+"bins"+"_FPR_vs_age_neutralAllele_GEAp" + str(p_threshold) +
            "_maf" + str(maf_filter) +
            "_equalInterval.png",
            dpi=300)
plt.close()



#Contrast the effect of selection and migration
#No selection
f1 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07_tick110000_100runs_p1e-10_maf0.05_cat22_fpr.tab"
df1 = pd.read_csv(f1, sep="\t", header=0, index_col=False)
f2 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K5000_r1.0e-07_tick110000_100runs_p1e-10_maf0.05_cat22_fpr.tab"
df2 = pd.read_csv(f2, sep="\t", header=0, index_col=False)

#1 environmental change
f3 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df3 = pd.read_csv(f3, sep="\t", header=0, index_col=False)
f4 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df4 = pd.read_csv(f4, sep="\t", header=0, index_col=False)

#Recurrent environmental changes
f5 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M3a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df5 = pd.read_csv(f5, sep="\t", header=0, index_col=False)
f6 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M3a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df6 = pd.read_csv(f6, sep="\t", header=0, index_col=False)

alpha_line=0.8
age_boundaries = list(df1["tick_text"]) + [110000.0]

# Neutral alleles: FPR ～ Allele age, equal intervals
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(df1["age"],
         df1["fpr"],
         color="grey",
         marker = "o",
         # fillstyle="none",
         linestyle='dotted',
         linewidth=2.0,
         alpha=alpha_line,
         label=" ")
plt.plot(df3["age"],
         df3["fpr"],
         color="mediumaquamarine",
         marker = "o",
         # fillstyle="none",
         linestyle='dotted',
         linewidth=2.0,
         alpha=alpha_line,
         label=" ")
plt.plot(df5["age"],
         df5["fpr"],
         color="teal",
         marker = "o",
         # fillstyle="none",
         linestyle='dotted',
         linewidth=2.0,
         alpha=alpha_line,
         label=" ")
plt.plot(df2["age"],
         df2["fpr"],
         color="grey",
         marker = "o",
         # linestyle='dashed',
         alpha=alpha_line,
         label=" No selection")
plt.plot(df4["age"],
         df4["fpr"],
         color="mediumaquamarine",
         marker = "o",
         # linestyle='dashed',
         alpha=alpha_line,
         label=" Single env. change")
plt.plot(df6["age"],
         df6["fpr"],
         color="teal",
         marker = "o",
         # linestyle='dashed',
         alpha=alpha_line,
         label=" Recurrent env. changes")
plt.ylim(min(df2["fpr"]*0.8), max(df4["fpr"])*1.1)
plt.legend(loc="upper center",
           title="   Migration \n Low    High",
           title_fontsize=legend_font,
           fontsize=legend_font,
           ncol=2,
           columnspacing=0.5)._legend_box.align = "left"
plt.xlabel("Allele age (thousand ticks)", fontsize=label_font)
plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=label_font)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i/1000)) for i in age_boundaries],
           rotation=90)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
# plt.title("", fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+"fpr_comparison2" +
            str(num_cat_age)+"bins"+"_FPR_vs_age_neutralAllele_GEAp" + str(p_threshold) +
            "_maf" + str(maf_filter) +
            "_equalInterval.png",
            dpi=300)
plt.close()

#Contrast the effect of selection and demographic history
#No selection
f1 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M0a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07_tick110000_100runs_p1e-10_maf0.05_cat22_fpr.tab"
df1 = pd.read_csv(f1, sep="\t", header=0, index_col=False)
f2 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M0b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K5000_r1.0e-07_tick110000_100runs_p1e-10_maf0.05_cat22_fpr.tab"
df2 = pd.read_csv(f2, sep="\t", header=0, index_col=False)

#1 environmental change
f3 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df3 = pd.read_csv(f3, sep="\t", header=0, index_col=False)
f4 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M2b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df4 = pd.read_csv(f4, sep="\t", header=0, index_col=False)

#Recurrent environmental changes
f5 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M3a_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df5 = pd.read_csv(f5, sep="\t", header=0, index_col=False)
f6 = "/home/anadem/github/data/tskit_data/output/mutiRuns/test/fpr/singleModel/Continuous_nonWF_M3b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07_tick110000_200runs_FPR.tab"
df6 = pd.read_csv(f6, sep="\t", header=0, index_col=False)

#Check the following numbers before use
alpha_line=0.8
age_boundaries = list(df1["tick_text"]) + [110000.0]

# Neutral alleles: FPR ～ Allele age, equal intervals
plt.figure(figsize=age_fig_size)
# plt.figure(figsize=(15,5)) # 100 bins
plt.plot(df1["age"],
         df1["fpr"],
         color="grey",
         marker = "s",
         # linestyle='dashed',
         # fillstyle="none",
         alpha=alpha_line,
         label="   ")
plt.plot(df3["age"],
         df3["fpr"],
         color="mediumaquamarine",
         marker = "s",
         # fillstyle="none",
         # linestyle='dashed',
         alpha=alpha_line,
         label="   ")
plt.plot(df5["age"],
         df5["fpr"],
         color="teal",
         marker = "s",
         # fillstyle="none",
         # linestyle='dashed',
         alpha=alpha_line,
         label="   ")
plt.plot(df2["age"],
         df2["fpr"],
         color="grey",
         marker = "<",
         # fillstyle="none",
         # linestyle='dashed',
         alpha=alpha_line,
         label=" No selection")
plt.plot(df4["age"],
         df4["fpr"],
         color="mediumaquamarine",
         marker = "<",
         # fillstyle="none",
         # linestyle='dashed',
         alpha=alpha_line,
         label=" Single env. change")
plt.plot(df6["age"],
         df6["fpr"],
         color="teal",
         marker = "<",
         # fillstyle="none",
         # linestyle='dashed',
         alpha=alpha_line,
         label=" Recurrent env. changes")
plt.ylim(min(df2["fpr"]*0.8), max(df4["fpr"])*1.18)
plt.legend(loc="upper center",
           title=" Demography \nConst.  Expan.",
           title_fontsize=legend_font,
           fontsize=legend_font,
           ncol=2,
           columnspacing=0.5)._legend_box.align = "left"
plt.xlabel("Allele age (thousand ticks)", fontsize=label_font)
plt.ylabel("False positive rate of neutral alleles \n (FP/(FP+TN))",
           fontsize=label_font)
plt.xticks(ticks=age_boundaries,
           labels=[str(int(i/1000)) for i in age_boundaries],
           rotation=90)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
# plt.title("", fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath+"fpr_comparison3" +
            str(num_cat_age)+"bins"+"_FPR_vs_age_neutralAllele_GEAp" + str(p_threshold) +
            "_maf" + str(maf_filter) +
            "_equalInterval.png",
            dpi=300)
plt.close()