"""
Analyze multiple tables of time-series samples generated by alleleAge_slimHistory_noNeuMut.py
Summarize and plot results from multiple runs and multiple times
tianlin.duan42@gmail.com
2025.03.27
Last modified on 2025.06.10
"""

############################# modules #########################################
import matplotlib
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np
import pandas as pd
import random
from time import time
import sys  # for sys.exit()
import os  # mkdir
import glob  #for loading files
from pingouin import ancova
from statsmodels.formula.api import ols #up to three decima
# from sklearn import linear_model
import statsmodels.api as sm

############################# options #########################################
import argparse
parser = argparse.ArgumentParser()
# Path should end by "/"
parser.add_argument('-i', '--input',
                    help='Path to the input tables',
                    type=str)
args = parser.parse_args()

############################# program #########################################
inPath = args.input
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M2b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07/timeSeries"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M2b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07/timeSeries"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M2b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07/timeSeries"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M2b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07/timeSeries"

# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M3b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07/timeSeries"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M3b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.06_mateD0.15_K17000_r1.0e-07/timeSeries"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M3b_glacialHistoryOptimum0_clineMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07/timeSeries"
# inPath = "/home/anadem/github/data/tskit_data/output/table/realistic_fpr_comparisons/selection/Continuous_nonWF_M3b_glacialHistoryOptimum0_patchyMap_mu1.0e-08_sigmaM0.01_sigmaW0.4_sigmaD0.03_mateD0.12_K17000_r1.0e-07/timeSeries"


history = 100000 # Ticks before the last environmental change (before the sampling stage)
#Use K80
expected_explained_proportion = 0.8
filePathList = glob.glob(inPath + "/*.txt")
fileNames = [filePath.split("/")[-1] for filePath in filePathList]
fileTicks = [int(fileName.split("_")[-3][4:]) for fileName in fileNames]
#Unique ticks
ticks = np.array(sorted(list(set(fileTicks))))
times = ticks - history
#Zoom in
times2 = np.array(sorted([i for i in list(set(times)) if i <= 10000]))
idx_zoom = [list(times).index(t) for t in list(times2)]
ticks = ticks.astype(str)
fileRunID = [fileName.split("_")[-4][4:] for fileName in fileNames]
runID_unique = list(set(fileRunID))
model_name = "_".join(fileNames[0].split("_")[0:-4])
fileSuffix = "_functionalMut_table.txt"
#Short title
if "sigmaD0.06_mateD0.15" in model_name:
    migName = "HighMig."
elif "sigmaD0.03_mateD0.12" in model_name:
    migName = "LowMig."
else:
    migName = ""
if "_clineMap_" in model_name:
    mapName = "Cline"
elif "_patchyMap_" in model_name:
    mapName = "Patchy"
else:
    mapName = ""
demoName_ori = model_name.split("_")[2]
# name_change = {"M2a":"M1a", "M2b":"M1b", "M3a":"M2a", "M3b":"M2b"}
name_change = {"M2a":"Single change", "M2b":"Single expansion", "M3a":"Recurrent changes", "M3b":"Recurrent expansions"}
demoName = name_change[demoName_ori]
shortName = ",".join([demoName, migName, mapName])

#Output
figPath = ("/home/anadem/github/data/tskit_data/figure/multiTimes/multiRun/test/"+
           model_name + "/")
if not os.path.exists(figPath):
    os.makedirs(figPath)
# outBasePath = "/home/tianlin/Documents/github/data/tskit_data/output/table/historical_optimum0_timeSeries/"

#Define categories
#1. Allele frequency
num_cat_freq = 10
freq_cats = np.append(np.arange(0, 1, 1.0 / num_cat_freq),1)

# 2. Time of mutations
num_cat_age = 20
mut_time_cats = np.append(np.arange(-history, max(times), (max(times) + history) / num_cat_age),
                          max(times))

# 3. Phenotypic effect size
# #Method1: Flexible categories
# # Read all files to determine the range of effect size: takes about 2 min
# maxSize = 0
# for runID in runID_unique:
#     fileList = np.char.add(np.char.add(np.array([inPath+"/"+model_name+"_seed"+runID+"_tick"]),
#                                    ticks),
#                        np.array([fileSuffix]))
#     df = pd.DataFrame()
#     for f in fileList:
#         df_focal = pd.read_csv(f, sep='\t', header=0)
#         df = pd.concat([df, df_focal], axis=0)
#     maxSize_focal = max(abs(df["mut_effect"]))
#     if maxSize_focal > maxSize:
#         maxSize = maxSize_focal
# num_cat_size = 20
# size_cats = np.append(np.arange(0,
#                                 maxSize,
#                                 maxSize / num_cat_size),
#                       maxSize + 0.0001)
#Method 2: Unified categories for all models
num_cat_size = 20 #
size_cats_step = 0.01
size_last_tick = 0.2 # temporary
lf_sum_positive_size = np.full(shape=(20, 100), fill_value=np.nan)
lf_sum_negative_size = np.full(shape=(20, 100), fill_value=np.nan)
size_cats = np.r_[np.arange(0, size_last_tick, size_cats_step), 1]



# Load multiple runs again and summarize data
df_summary = pd.DataFrame()
df_lf_freq_positive = pd.DataFrame()
df_lf_age_positive = pd.DataFrame()
df_lf_size_positive = pd.DataFrame()
df_lf_freq_negative = pd.DataFrame()
df_lf_age_negative = pd.DataFrame()
df_lf_size_negative = pd.DataFrame()
j = 0
for runID in runID_unique:
    fileList = np.char.add(np.char.add(np.array([inPath+"/"+model_name+"_seed"+runID+"_tick"]),
                                   ticks),
                       np.array([fileSuffix]))
    df = pd.DataFrame()
    i = 0
    LFs = []
    LFs_positive = []
    LFs_negatie = []
    k_positive = [] #K80(positve)
    k_net = [] #K80(nete)
    # Load multiple ticks of one run
    for f in fileList:
        focal_tick = times[i]
        df_focal = pd.read_csv(f, sep='\t', header=0)
        # Add relative lf_mut,temporary run ID, and rank of p-values
        #Sum of positve allelic effect on local adaptation
        positive_lf_mut = df_focal.loc[df_focal["lf_mut"] > 0, "lf_mut"]
        lf_sum_positive = sum(positive_lf_mut)
        LFs_positive.append(lf_sum_positive)
        #Sum of negative allelic effect on local adaptation
        LFs_negatie.append(sum(df_focal.loc[df_focal["lf_mut"] < 0, "lf_mut"]))
        #Sum of all allelic effects on local adaptation
        lf_sum = sum(df_focal["lf_mut"])
        LFs.append(lf_sum)
        #LFmut relative to positive sum
        df_focal["relative_positive_lf"] = (df_focal["lf_mut"] /
                                                  lf_sum_positive)
        #LFmut relative to total effect of all alleles
        df_focal["relative_lf"] = df_focal["lf_mut"] / lf_sum
        df_focal["time"] = np.full(shape=(df_focal.shape[0], 1),
                                             fill_value=focal_tick)
        df = pd.concat([df, df_focal], axis=0)

        # Minimum number of alleles for explaining at least 80% positive allelic LF K80(positive)
        sorted_lf_mut_positve = np.array(list(reversed(sorted(positive_lf_mut))))
        cumulative_lf_positve = [0] + [sum(sorted_lf_mut_positve[0:k + 1]) / lf_sum_positive
                               for k in range(len(sorted_lf_mut_positve))]
        # How many alleles do we need to account for 80% of current local adaptation?
        gea_goal_positve = sum(np.array(cumulative_lf_positve) < expected_explained_proportion)
        k_positive.append(gea_goal_positve)

        # Minimum number of alleles for explaining at least 80% NET allelic LF: K80(net)
        sorted_lf_mut_positve = np.array(list(reversed(sorted(positive_lf_mut))))
        cumulative_lf_net = [0] + [sum(sorted_lf_mut_positve[0:k + 1]) / lf_sum
                               for k in range(len(sorted_lf_mut_positve))]
        # How many alleles do we need to account for 80% of current local adaptation?
        gea_goal_net = sum(np.array(cumulative_lf_net) < expected_explained_proportion)
        k_net.append(gea_goal_net)
        i += 1
    j += 1
    print(str(i) + "files of run " + str(j) + " have been loaded.")
    df_summary_focal = pd.DataFrame({"lf": LFs,
                                     "lf_positive": LFs_positive,
                                     "lf_negative": LFs_negatie,
                                     "k_net": k_net,
                                     "k_positive": k_positive,
                                     "runID": runID,
                                     "times": times})
    df_summary = pd.concat([df_summary, df_summary_focal], axis=0)

    # Contribution to local adaptation (sum(positive LF_mut)) from alleles of each frequency bin
    lf_by_freq_positive = np.full(shape=(num_cat_freq, len(times)), fill_value=np.nan)
    lf_by_freq_negative = np.full(shape=(num_cat_freq, len(times)), fill_value=np.nan)
    for t in range(len(times)):
        focal_time = times[t]
        # focal_lf_mut = df[df["time"] == focal_time]["relative_lf"] # Relative
        focal_lf_mut = df[df["time"] == focal_time]["lf_mut"]
        focal_freq = df[df["time"] == focal_time]["freq"]
        for i in range(num_cat_freq):
            lf_category = focal_lf_mut[np.logical_and(focal_freq > freq_cats[i],
                                                      focal_freq <= freq_cats[
                                                          i + 1])]
            lf_by_freq_positive[i][t] = sum(lf_category[lf_category > 0])
            lf_by_freq_negative[i][t] = sum(lf_category[lf_category < 0])
    df_lf_freq_positive = pd.concat([df_lf_freq_positive, pd.DataFrame(lf_by_freq_positive)])
    df_lf_freq_negative = pd.concat([df_lf_freq_negative, pd.DataFrame(lf_by_freq_negative)])

    # Relative contribution (sum(positive LF_mut)) from alleles of each mutation time bin
    # Time of mutations; 0 is the time of the start of the final environental change
    lf_by_muttime_positive = np.full(shape=(num_cat_age, len(times)), fill_value=np.nan)
    lf_by_muttime_negative = np.full(shape=(num_cat_age, len(times)), fill_value=np.nan)
    for t in range(len(times)):
        focal_time = times[t]
        focal_lf_mut = df[df["time"] == focal_time]["lf_mut"]
        focal_age = df[df["time"] == focal_time]["age"]
        focal_mut_time = times[t] - focal_age
        for i in range(num_cat_age):
            lf_category = focal_lf_mut[np.logical_and(focal_mut_time > mut_time_cats[i],
                                                      focal_mut_time <= mut_time_cats[
                                                          i + 1])]
            lf_by_muttime_positive[i][t] = sum(lf_category[lf_category > 0])
            lf_by_muttime_negative[i][t] = sum(lf_category[lf_category < 0])
    df_lf_age_positive = pd.concat([df_lf_age_positive, pd.DataFrame(lf_by_muttime_positive)])
    df_lf_age_negative = pd.concat([df_lf_age_negative, pd.DataFrame(lf_by_muttime_negative)])

    # Contribution to local adaptation (sum(positive LF_mut)) from alleles of each SIZE bin
    lf_by_size_positive = np.full(shape=(num_cat_size, len(times)), fill_value=np.nan)
    lf_by_size_negative = np.full(shape=(num_cat_size, len(times)), fill_value=np.nan)
    time_sum = []
    for t in range(len(times)):
        focal_time = times[t]
        # focal_lf_mut = df[df["time"] == focal_time]["relative_lf"] # Relative
        focal_lf_mut = df[df["time"] == focal_time]["lf_mut"]
        focal_size = abs(df[df["time"] == focal_time]["mut_effect"])
        for i in range(num_cat_size):
            lf_category = focal_lf_mut[np.logical_and(focal_size > size_cats[i],
                                                      focal_size <= size_cats[
                                                          i + 1])]
            lf_by_size_positive[i][t] = sum(lf_category[lf_category > 0])
            lf_by_size_negative[i][t] = sum(lf_category[lf_category < 0])
    df_lf_size_positive = pd.concat([df_lf_size_positive, pd.DataFrame(lf_by_size_positive)])
    df_lf_size_negative = pd.concat([df_lf_size_negative, pd.DataFrame(lf_by_size_negative)])

#Median of all runs
df_summary_median = df_summary.drop(columns=["runID"]).groupby(["times"]).median()

#Separate generation 1000-10000
df_summary_myTime = df_summary[(df_summary["times"] >= 1000) & (df_summary["times"] <= 10000)]
#time in 1000 generation unit
df_summary_myTime["times"]=df_summary_myTime["times"]/1000
# stats.linregress(df_summary_myTime["times"],df_summary_myTime["k_net"])
# stats.linregress(df_summary_myTime["times"],df_summary_myTime["k_positive"])

#Reshape
df_summary_myTime_melt = df_summary_myTime.melt(id_vars="times", value_vars=["k_net","k_positive"],
                                                var_name="lf_type", value_name="k80")
model1 = ols('k80 ~ lf_type * times', data=df_summary_myTime_melt).fit()

# Print the summary of the model
print(model1.summary())
anova_result = sm.stats.anova_lm(model1, type=2)



#Plots
label_font = 16
tick_font = 16
legend_font = 15



# df_summary_median_myTime = df_summary_median[(df_summary_median.index >= 1000)
#                                              & (df_summary_median.index <= 10000)]
# stats.linregress(df_summary_median_myTime.index,df_summary_median_myTime["k_net"])
# stats.linregress(df_summary_median_myTime.index,df_summary_median_myTime["k_positive"])

#Use mean instead of median for most plots
df_freq_positive_median = df_lf_freq_positive.groupby(level=0).mean()
df_age_positive_median = df_lf_age_positive.groupby(level=0).mean()
df_size_positive_median = df_lf_size_positive.groupby(level=0).mean()
df_freq_negative_median = df_lf_freq_negative.groupby(level=0).mean()
df_age_negative_median = df_lf_age_negative.groupby(level=0).mean()
df_size_negative_median = df_lf_size_negative.groupby(level=0).mean()



# Three types of Sigma(LF_mut) ~ time
alpha_singleRun = 0.08
alpha_mean = 0.9

plt.figure(figsize=(9,5))
plt.axhline(y=0, linestyle="dotted", color="grey")
#Positive LF
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"], focal_run["lf_positive"],
             marker="", markersize=5, markerfacecolor="white",
             color="lightseagreen", alpha=alpha_singleRun)
plt.plot(times, df_summary_median["lf_positive"],
         marker="o", markersize=5, markerfacecolor="white",
         color="lightseagreen", alpha=alpha_mean,
         linewidth=2.0,
         label=r"Sum of positive $\it{LF_{mut}}$")
#Negative LF
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"], focal_run["lf_negative"],
             marker="", markersize=5, markerfacecolor="white",
             color="firebrick", alpha=alpha_singleRun)
plt.plot(times, df_summary_median["lf_negative"],
             marker="o", markersize=5, markerfacecolor="white",
             color="firebrick", alpha=alpha_mean,
         linewidth=2.0,
         label=r"Sum of negative $\it{LF_{mut}}$")
# Net LF
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"], focal_run["lf"],
             marker="", markersize=5, markerfacecolor="white",
             color="grey", alpha=alpha_singleRun)
plt.plot(times, df_summary_median["lf"],
             marker="o", markersize=5, markerfacecolor="white",
             color="dimgrey", alpha=alpha_mean,
         linewidth=2.0,
         label=r"Net sum")
plt.xlabel("Ticks after the last environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ($\it{\Sigma LF_{mut}}$ )",
           fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.legend(title_fontsize=label_font,
           fontsize=label_font)
plt.tight_layout()
plt.savefig(figPath + model_name  + "_20RunsMedian_allelicLF.png",
            dpi=300)
plt.close()



# k80(positive) ~ time
plt.figure(figsize=(9,5))
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"], focal_run["k_positive"],
             marker="", markersize=5, markerfacecolor="white",
             color="grey", alpha=alpha_singleRun)
plt.plot(times, df_summary_median["k_positive"],
         marker="o", markersize=5, markerfacecolor="white",
         color="dimgrey", alpha=alpha_mean,
         linewidth=2.0,
         label=r"Net sum")
plt.xlabel("Ticks after the last environmental change",
           fontsize=label_font)
plt.ylabel(r"$K_{80, pos}$",
           fontsize=label_font)
plt.title(shortName, fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.tight_layout()
plt.savefig(figPath + model_name + "_20RunsMedian_k" +
            str(int(expected_explained_proportion*100)) +
            "positve.png",
            dpi=300)
plt.close()

# k80(net) and k80(positive) ~ time
plt.figure(figsize=(9,5))
#k80 net
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"], focal_run["k_net"],
             marker="", markersize=5, markerfacecolor="white",
             color="grey", alpha=alpha_singleRun)
plt.plot(times, df_summary_median["k_net"],
         marker="o", markersize=5, markerfacecolor="white",
         color="dimgrey", alpha=alpha_mean,
         linewidth=2.0,
         label=r"$K_{80,net}$")
#k80 positive
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"], focal_run["k_positive"],
             marker="", markersize=5, markerfacecolor="white",
             color="lightseagreen", alpha=alpha_singleRun)
plt.plot(times, df_summary_median["k_positive"],
             marker="o", markersize=5, markerfacecolor="white",
             color="lightseagreen", alpha=alpha_mean,
         label=r"$K_{80,pos}$")
plt.xlabel("Ticks after the last environmental change",
           fontsize=label_font)
plt.ylabel("Minimum number of alleles for \n explaining 80% local adaptation "+ r"($K_{80}$)",
           fontsize=label_font)
plt.title(shortName, fontsize=label_font)
plt.legend(title_fontsize=label_font,
           fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.tight_layout()
plt.savefig(figPath + model_name + "_20RunsMedian_k" +
            str(int(expected_explained_proportion*100)) +
            "net.png", dpi=300)
plt.close()

# Zoom in: k80(net) and k80(positive) ~ time
plt.figure(figsize=(6.5,5))
#k80 net
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"][idx_zoom], focal_run["k_net"][idx_zoom],
             marker="", markersize=5, markerfacecolor="white",
             color="grey", alpha=alpha_singleRun)
plt.plot(times2, df_summary_median["k_net"][times2],
         marker="o", markersize=5, markerfacecolor="white",
         color="dimgrey", alpha=alpha_mean,
         linewidth=2.0,
         label=r"$K_{80,net}$")
#k80 positive
for runID in runID_unique:
    focal_run = df_summary[df_summary["runID"] == runID]
    plt.plot(focal_run["times"][idx_zoom], focal_run["k_positive"][idx_zoom],
             marker="", markersize=5, markerfacecolor="white",
             color="lightseagreen", alpha=alpha_singleRun)
plt.plot(times2, df_summary_median["k_positive"][times2],
             marker="o", markersize=5, markerfacecolor="white",
             color="lightseagreen", alpha=alpha_mean,
         label=r"$K_{80,pos}$")
plt.xlabel("Ticks after the last environmental change",
           fontsize=label_font)
plt.ylabel("Minimum number of alleles for \n explaining 80% local adaptation "+ r"($K_{80}$)",
           fontsize=label_font)
plt.legend(title_fontsize=label_font,
           fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.tight_layout()
# plt.title(shortName, fontsize=label_font)
plt.savefig(figPath + model_name + "_20RunsMedian_k" +
            str(int(expected_explained_proportion*100)) +
            "net_zoom10000.png", dpi=300)
plt.close()


# # median freq ~ time
# median_freqs = []
# for t in times:
#     focal_median = np.median(df[df["time"] == t]["freq"])
#     median_freqs.append(focal_median)
#
# plt.figure(figsize=(12,5))
# plt.plot(times, median_freqs,
#          marker="o", markersize=5, markerfacecolor="white",
#          color="black")
# plt.xlabel("Ticks after the environmental change")
# plt.ylabel("Median allele frequency of segregating functional mutations")
# plt.savefig(figPath + model_name + "_medianFreq_through_time_100000.png",
#             dpi=300)
# plt.close()

# # median absolute size ~ time
# median_sizes = []
# for t in times:
#     focal_median = np.median(abs(df[df["time"] == t]["mut_effect"]))
#     median_sizes.append(focal_median)
#
# plt.figure(figsize=(12,5))
# plt.plot(times, median_sizes,
#          marker="o", markersize=5, markerfacecolor="white",
#          color="black")
# plt.xlabel("Ticks after the environmental change")
# plt.ylabel("Median phenotypic effect size of segregating functional mutations")
# plt.savefig(figPath + model_name + "_medianAbsSize_through_time_100000.png",
#             dpi=300)
# plt.close()



# Plot contribution to local adaptation (sum(positive LF_mut)) from alleles of each frequency bin
freq10colors = ["#d2ebf3FF", "#9dcde3FF", "#6899CEFF", "#4074cbFF", "#1839aaFF",
                "#1624a1FF", "#523cb7FF", "#8f69caFF", "#c2a0dfFF", "#e5d0f0FF"]
freq_labels = ["0-0.1", "0.1-0.2", "0.2-0.3", "0.3-0.4", "0.4-0.5",
               "0.5-0.6", "0.6-0.7", "0.7-0.8", "0.8-0.9", "0.9-1.0"]

# Stacked area, contribution of frequency bins ~ time， 0 - 100 000, add negatives
plt.figure(figsize=(12, 5))
plt.stackplot(times, df_freq_positive_median,
              colors=freq10colors,
              labels=freq_labels)
plt.stackplot(times, df_freq_negative_median,
              colors=freq10colors,
              labels="")
plt.axhline(y=0, color="grey", linestyle="dotted")
plt.xlabel("Ticks after the last environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ ) ",
           fontsize=label_font)
# plt.ylim(0, 1.4)
plt.legend(title="     Allele frequency    ",
           loc=(1.05, 0.075),
           # loc = "center right",
           reverse=True,
           ncol=1,
           title_fontsize=15,
           fontsize=15,
           labelspacing = 0.3)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
# plt.savefig(figPath + model_name + "_median20Runs_lfByFreq10Bin_stack.png",
#             dpi=300)
plt.savefig(figPath + model_name + "_20RunsMean_lfByFreq10Bin_stack.png",
            dpi=300)
plt.close()

# Zoom in,
# Stacked area, contribution of frequency bins ~ time
# freq10colors = ["#d2ebf3FF", "#9dcde3FF", "#6899CEFF", "#4074cbFF", "#1839aaFF",
#                 "#1624a1FF", "#523cb7FF", "#8f69caFF", "#c2a0dfFF", "#e5d0f0FF"]
# freq_labels = ["0-0.1", "0.1-0.2", "0.2-0.3", "0.3-0.4", "0.4-0.5",
#                "0.5-0.6", "0.6-0.7", "0.7-0.8", "0.8-0.9", "0.9-1.0"]
# index10000 = int(np.where(times == 10000)[0])
# maxY = np.sum(lf_by_freq_positive, axis=0)[index10000] * 1.1
plt.figure(figsize=(8, 5))
plt.stackplot(times2, df_freq_positive_median.iloc[:, idx_zoom],
              colors=freq10colors,
              labels=freq_labels)
plt.stackplot(times2, df_freq_negative_median.iloc[:, idx_zoom],
              colors=freq10colors,
              labels="")
plt.axhline(y=0, linestyle="dotted", color="grey")
plt.xlabel("Ticks after the last environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ ) ",
           fontsize=label_font)
plt.legend(title="    Allele frequency    ",
           loc=(1.05, 0.075),
           # loc = "center right",
           reverse=True,
           ncol=1,
           title_fontsize=15,
           fontsize=15,
           labelspacing = 0.3)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
# plt.savefig(figPath + model_name + "_median20Runs_lfByFreq10Bin_stack_zoomIn.png",
#             dpi=300)
plt.savefig(figPath + model_name + "_20RunsMean_lfByFreq10Bin_stack_zoomIn.png",
            dpi=300)
plt.close()



# Plot the relative contribution (sum(positive LF_mut)) from alleles of each mutation time bin
# Time of mutations; 0 is the time of the start of the final environental change
age20colors = ["#FCFDBF", "#FDE4A6", "#FECC8F", "#FEB37B", "#FD9A6A",
               "#FA815F", "#F4685C", "#E85362", "#D6456C", "#C03A76",
               "#AB337C", "#952C80", "#802582", "#6B1D81", "#56147D",
               "#400F73", "#29115B", "#160F3B", "#07061D", "#000004"]
time20colors = list(reversed(age20colors))
mut_time_labels = ["-".join([str(int(mut_time_cats[i]/10000)),
                             str(int(mut_time_cats[i + 1]/10000))])
                   for i in range(num_cat_age)]
# Stacked area, contribution of frequency bins ~ time， 0 - 100 000，add negative
plt.figure(figsize=(12, 5))
plt.stackplot(times, df_age_positive_median,
              colors=time20colors,
              labels=mut_time_labels)
plt.stackplot(times, df_age_negative_median,
              colors=time20colors,
              labels="")
plt.axhline(y=0, color="grey", linestyle="dotted")
plt.xlabel("Ticks after the environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ( $\it{\Sigma LF_{mut}}$) ",
           fontsize=label_font)
# plt.ylim(0, 1.4)
plt.legend(loc=(1.05, -0.15),
           title="Mutation time (x$10^{4}$ " +"\n" + "ticks after env. change)",
           reverse=True,
           ncol=1,
           title_fontsize=15,
           fontsize=15,
           columnspacing=0.5,
           labelspacing = 0.05)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
# plt.savefig(figPath + model_name + "_20RunsMedian_lfByMutTime_20Bin_stack.png",
#             dpi=300)
plt.savefig(figPath + model_name + "_20RunsMean_lfByMutTime_20Bin_stack.png",
            dpi=300)
plt.close()

# Zoom in, stacked area, contribution of frequency bins ~ time， 0 - 100 000，add negative
plt.figure(figsize=(8, 5))
plt.stackplot(times2, df_age_positive_median.iloc[:, idx_zoom],
              colors=time20colors,
              labels=mut_time_labels)
plt.stackplot(times2, df_age_negative_median.iloc[:, idx_zoom],
              colors=time20colors,
              labels="")
plt.axhline(y=0, color="grey", linestyle="dotted")
plt.xlabel("Ticks after the environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ ) ",
           fontsize=label_font)
# plt.ylim(0, 1.4)
plt.legend(loc=(1.06, -0.15),
           title="Mutation time (x$10^{4}$ " +"\n" + "ticks after env. change)",
           reverse=True,
           ncol=1,
           title_fontsize=15,
           fontsize=15,
           columnspacing=0.5,
           labelspacing = 0.05)
plt.title(shortName, fontsize=label_font)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.tight_layout()
# plt.savefig(figPath + model_name + "_20RunsMedian_lfByMutTime_20Bin_stack_zoomIn.png",
#             dpi=300)
plt.savefig(figPath + model_name + "_20RunsMean_lfByMutTime_20Bin_stack_zoomIn.png",
            dpi=300)
plt.close()



# Plot the contribution to local adaptation (sum(positive LF_mut)) from alleles of each SIZE bin
# Colors copied from
# /home/tianlin/Documents/github/arg-for-gea/R/play_with_colors.R
# #viridis
# size20colors = ["#FDE725", "#DCE318", "#B8DE29", "#94D840", "#74D055",
#                 "#56C667", "#3CBB75", "#29AF7F", "#20A386", "#1F968B",
#                 "#238A8D", "#287D8E", "#2D718E", "#32648E", "#39558C",
#                 "#3F4788", "#453781", "#482677", "#481567", "#440154"]
#Modified viridis
size20colors = ["#FDE725FF", "#cce010FF", "#a2d115FF", "#68cf1fFF", "#34c421FF",
                "#2bba44FF", "#3CBB75FF","#29AF7FFF", "#20A387FF", "#1F968BFF",
                "#238A8DFF", "#287D8EFF","#2D708EFF", "#33638DFF", "#39568CFF",
                "#404788FF", "#453781FF","#482677FF", "#481567FF", "#440154FF"]
size_labels = [" – ".join([str(round(size_cats[i], 3)),
                           str(round(size_cats[i + 1], 3))])
               for i in range(num_cat_size)]
size_labels[-1] = ">" + str(size_cats[-2])

# Stacked area, contribution of size bins ~ time， 0 - 100 000, add negative
plt.figure(figsize=(12, 5))
plt.stackplot(times, df_size_positive_median,
              colors=size20colors,
              labels=size_labels)
plt.stackplot(times, df_size_negative_median,
              colors=size20colors,
              labels="")
plt.axhline(y=0, color="grey", linestyle="dotted")
plt.xlabel("Ticks after the environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ ) ",
           fontsize=label_font)
# plt.ylim(0, 1.4)
# plt.legend(loc=(1.03, -0.1),
#            title="|Phenotypic effect size|",
#            reverse=True,
#            ncol=1, fontsize="medium")
plt.legend(loc=(1.05, -0.15),
           title="|Phenotypic effect size|",
           reverse=True,
           ncol=1,
           title_fontsize=15,
           fontsize=15,
           labelspacing=0.05,
           columnspacing=-0.5)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
# plt.savefig(figPath + model_name +
#             "_20Runsmedian_lfBysize20Bin_stack.png",
#             dpi=300)
plt.savefig(figPath + model_name +
            "_20RunsMean_lfBysize20Bin_stack.png",
            dpi=300)
plt.close()

# Zoom in, 0 - 10 000
# Stacked area, contribution of size bins ~ time
plt.figure(figsize=(8, 5))
plt.stackplot(times2, df_size_positive_median.iloc[:, idx_zoom],
              colors=size20colors,
              labels=size_labels)
plt.stackplot(times2, df_size_negative_median.iloc[:, idx_zoom],
              colors=size20colors,
              labels="")
plt.axhline(y=0, color="grey", linestyle="dotted")
plt.xlabel("Ticks after the environmental change",
           fontsize=label_font)
plt.ylabel(r"Contribution to local adaptation ( $\it{\Sigma LF_{mut}}$ ) ",
           fontsize=label_font)
# plt.ylim(0, 1.4)
plt.legend(loc=(1.05, -0.15),
           title="|Phenotypic effect size|",
           reverse=True,
           ncol=1,
           title_fontsize=15,
           fontsize=15,
           # handletextpad=-1.2,
           labelspacing=0.05,
           columnspacing=-0.5)
plt.tick_params(axis='both', which='major', labelsize=tick_font)
plt.title(shortName, fontsize=label_font)
plt.tight_layout()
# plt.savefig(figPath + model_name +
#             "_20Runsmedian_lfBysize20Bin_stack_zoomIn.png",
#             dpi=300)
plt.savefig(figPath + model_name +
            "_20RunsMean_lfBysize20Bin_stack_zoomIn.png",
            dpi=300)
plt.close()
